ALTER TABLE `ADMEXTRACTOS`.`EBS$ADDRESSTYPE` MODIFY `DESCRIPTION` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$ADDRESSTYPE` MODIFY `SHORTNAME` VARCHAR(8) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$ADDRESSTYPE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$CITY
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$CITY` ADD CONSTRAINT `EBS$CITY_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$CITY` MODIFY `STATEID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$CITY` MODIFY `NAME` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$CITY` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$COLLECTADDRESSTYPE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$COLLECTADDRESSTYPE` MODIFY `DESCRIPTION` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COLLECTADDRESSTYPE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$COMPANY
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$COMPANY_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `MONEYID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `COMPANYTYPEID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `LANGUAGEID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `NAME` VARCHAR(100) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `IDENTIFICATIONCODE` VARCHAR(18) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `IDENTIFICATIONTYPEID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `CODE` SMALLINT NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$COMPANYTYPE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANYTYPE` ADD CONSTRAINT `EBS$COMPANYTYPE_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANYTYPE` MODIFY `DESCRIPTION` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANYTYPE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$COUNTRY
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$COUNTRY` ADD CONSTRAINT `EBS$COUNTRY_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COUNTRY` MODIFY `NAME` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COUNTRY` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$IDENTIFICATIONTYPE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$IDENTIFICATIONTYPE` ADD CONSTRAINT `EBS$IDENTIFICATIONTYPE_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$IDENTIFICATIONTYPE` MODIFY `NAME` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$IDENTIFICATIONTYPE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$INSTRUCTION
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$INSTRUCTION` MODIFY `INSTRUCTION` VARCHAR(2000) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$INSTRUCTION` MODIFY `ACTION` VARCHAR(1) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$INSTRUCTION` MODIFY `TABLENAME` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$INSTRUCTION` MODIFY `BILLPERIODID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$INSTRUCTION` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$LANGUAGE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$LANGUAGE` ADD CONSTRAINT `EBS$LANGUAGE_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$LANGUAGE` MODIFY `NAME` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$LANGUAGE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$MEASUREMENTUNIT
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$MEASUREMENTUNIT` ADD CONSTRAINT `EBS$MEASUREMENTUNIT_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MEASUREMENTUNIT` MODIFY `DESCRIPTION` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MEASUREMENTUNIT` MODIFY `SHORTNAME` VARCHAR(8) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MEASUREMENTUNIT` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$MONEY
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEY` ADD CONSTRAINT `EBS$MONEY_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEY` MODIFY `SYMBOL` VARCHAR(3) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEY` MODIFY `NAME` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEY` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$MONEYCHANGERATE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEYCHANGERATE` ADD CONSTRAINT `EBS$MONEYCHANGERATE_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEYCHANGERATE` MODIFY `CREATEDATE` DATETIME NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEYCHANGERATE` MODIFY `VALUE` DECIMAL(13,6) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEYCHANGERATE` MODIFY `MONEYID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$MONEYCHANGERATE` MODIFY `ID` DOUBLE NOT NULL;-- ------------------------------------------------------
--  Constraints for Table EBS$RETENTIONTAXSERVICE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$RETENTIONTAXSERVICE` MODIFY `PERCENTAGE`DECIMAL(5,2) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$RETENTIONTAXSERVICE` MODIFY `SERVICEID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$RETENTIONTAXSERVICE` MODIFY `COMPANYID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$RETENTIONTAXSERVICE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$STATE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATE` ADD CONSTRAINT `EBS$STATE_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATE` MODIFY `COUNTRYID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATE` MODIFY `NAME` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$STATUS
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATUS` ADD CONSTRAINT `EBS$STATUS_IK` PRIMARY KEY (`ID`);
  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATUS` MODIFY `DESCRIPTION` VARCHAR(50) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATUS` MODIFY `ACTIONCODE` VARCHAR(16) NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATUS` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Constraints for Table EBS$TRIBUTARYCOMPANYTYPE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$TRIBUTARYCOMPANYTYPE` MODIFY `COMPANYID` DOUBLE NOT NULL ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$TRIBUTARYCOMPANYTYPE` MODIFY `ID` DOUBLE NOT NULL ;
-- ------------------------------------------------------
--  Ref Constraints for Table EBS$CITY
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$CITY` ADD CONSTRAINT `EBS$CITYSTATE_F` FOREIGN KEY (`STATEID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$STATE` (`ID`) ;
-- ------------------------------------------------------
--  Ref Constraints for Table EBS$COMPANY
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$CMPNYCITY_F` FOREIGN KEY (`CITYID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$CITY` (`ID`) ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$CMPNYCMPNYTYPE_F` FOREIGN KEY (`COMPANYTYPEID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$COMPANYTYPE` (`ID`) ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$CMPNYIDNTFCTIONTYPE_F` FOREIGN KEY (`IDENTIFICATIONTYPEID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$IDENTIFICATIONTYPE` (`ID`) ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$CMPNYLANGUAGE_F` FOREIGN KEY (`LANGUAGEID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$LANGUAGE` (`ID`) ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$CMPNYLEAFNODE_F` FOREIGN KEY (`LEAFNODEID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$COMPANY` (`ID`) ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$CMPNYMONEY_F` FOREIGN KEY (`MONEYID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$MONEY` (`ID`) ;
  ALTER TABLE `ADMEXTRACTOS`.`EBS$COMPANY` ADD CONSTRAINT `EBS$CMPNYROOTNODE_F` FOREIGN KEY (`ROOTNODEID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$COMPANY` (`ID`) ;
-- ------------------------------------------------------
--  Ref Constraints for Table EBS$STATE
-- ------------------------------------------------------

  ALTER TABLE `ADMEXTRACTOS`.`EBS$STATE` ADD CONSTRAINT `EBS$STATECOUNTRY_F` FOREIGN KEY (`COUNTRYID`)
	  REFERENCES `ADMEXTRACTOS`.`EBS$COUNTRY` (`ID`) ;
