
  ALTER TABLE `EIS$ACCOUNTBALANCE_` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`BALANCEAGREEAFTERBILL` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`BALANCEAGREEBEROFEBILL` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`CLAIMPAYMENTNONPAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`CLAIMVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`PAYMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`INSTALLMENTBALANCE2AGREE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`BALANCE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTBALANCE_0001
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_0001_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0001` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTBALANCE_0002
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_0002_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0002` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTBALANCE_0003
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_0003_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0003` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTBALANCE_0004
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_0004_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0004` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTBALANCE_0005
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_0005_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0005` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTBALANCE_0006
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_0006_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_0006` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTBALANCE_OVFLW
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` ADD CONSTRAINT `EIS$ACCOUNTBALANCE_OVFLW_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTBALANCE_OVFLW` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ACCOUNTCOLLECT
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTCOLLECT` ADD CONSTRAINT `EIS$ACCOUNTCOLLECT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ACCOUNTCOLLECT` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTCOLLECT` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTCOLLECT` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTCOLLECT` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTCOLLECT` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTCOLLECT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ACCOUNTCOLLECT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ADDRESS
-- ------------------------------------------------------

  ALTER TABLE `EIS$ADDRESS` ADD CONSTRAINT `EIS$ADDRESS_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ADDRESS` MODIFY (`ISSTANDARD` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESS` MODIFY (`GEOLOCATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESS` MODIFY (`SOCIALLAYERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESS` MODIFY (`ADDRESS` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESS` MODIFY (`ADDRESSTYPE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESS` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$ADDRESSCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$ADDRESSCHANGE` ADD CONSTRAINT `EIS$ADDRESSCHANGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$ADDRESSCHANGE` MODIFY (`REQUESTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESSCHANGE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESSCHANGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$ADDRESSCHANGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$AGREECOLLECTADDRESS
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREECOLLECTADDRESS` ADD CONSTRAINT `EIS$AGREECOLLECTADDRESS_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$AGREECOLLECTADDRESS` MODIFY (`COLLECTADDRESS` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREECOLLECTADDRESS` MODIFY (`COLLECTADDRESSTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREECOLLECTADDRESS` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREECOLLECTADDRESS` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREECOLLECTADDRESS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$AGREEMENT
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENT` ADD CONSTRAINT `EIS$AGREEMENT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`CLAIMPAYMENTNONPAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`CLAIMVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`BALANCE2AGREE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`BALANCE2COMPANY` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`BILLPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$AGREEMENTSERVICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENTSERVICE` ADD CONSTRAINT `EIS$AGREEMENTSERVICE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`CLAIMPAYMENTNONPAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`CLAIMVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`BALANCE2COMPANY` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`PENDINGACCOUNTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`USERPAYMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$AGREEMENTSERVICECONCEPT
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENTSERVICECONCEPT` ADD CONSTRAINT `EIS$AGREEMENTSERVICECONCEPT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$AGREEMENTSERVICECONCEPT` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICECONCEPT` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICECONCEPT` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICECONCEPT` MODIFY (`AGREEMENTSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICECONCEPT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICECONCEPT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$AGREEMENTSERVICEUSER
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` ADD CONSTRAINT `EIS$AGREEMENTSERVICEUSER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`CLAIMPAYMENTNONPAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`CLAIMVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`BALANCE2USER` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`BALANCE2COMPANY` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`PENDINGACCOUNTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`USERPAYMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`AGREEMENTSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$AGREEMENTUSER
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENTUSER` ADD CONSTRAINT `EIS$AGREEMENTUSER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`CLAIMPAYMENTNONPAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`CLAIMVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`BALANCE2USER` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`BALANCE2COMPANY` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`USERPAYMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$AGREEMENTUSER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$BILLCYCLE
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLCYCLE` ADD CONSTRAINT `EIS$BILLCYCLE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$BILLCYCLE` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLCYCLE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLCYCLE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLCYCLE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$BILLPERIOD
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLPERIOD` ADD CONSTRAINT `EIS$BILLPERIOD_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`FINALDATECTLPAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`INITDATECTLPAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`FINALDATECTLMOVEMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`INITDATECTLMOVEMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`PAYMENTDATELIMIT` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`FINALDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`INITIALDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPERIOD` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$BILLPLAN
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLPLAN` ADD CONSTRAINT `EIS$BILLPLAN_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$BILLPLAN` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLAN` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLAN` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$BILLPLANCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLPLANCHANGE` ADD CONSTRAINT `EIS$BILLPLANCHANGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$BILLPLANCHANGE` MODIFY (`REQUESTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCHANGE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCHANGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCHANGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$BILLPLANCONCEPT
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLPLANCONCEPT` ADD CONSTRAINT `EIS$BILLPLANCONCEPT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$BILLPLANCONCEPT` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCONCEPT` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCONCEPT` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCONCEPT` MODIFY (`BILLPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCONCEPT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLPLANCONCEPT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$BILLSTATUS
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLSTATUS` ADD CONSTRAINT `EIS$BILLSTATUS_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$BILLSTATUS` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLSTATUS` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$BILLSTATUS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CASHMAN
-- ------------------------------------------------------

  ALTER TABLE `EIS$CASHMAN` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `EIS$CASHMAN` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CASHMAN` MODIFY (`COLLECTIONBRANCHID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CASHMAN` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CASHMAN` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CASHMAN` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CLAIMOBSERVATION
-- ------------------------------------------------------

  ALTER TABLE `EIS$CLAIMOBSERVATION` ADD CONSTRAINT `EIS$CLAIMOBSERVATION_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$CLAIMOBSERVATION` MODIFY (`OBSERVATION` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLAIMOBSERVATION` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLAIMOBSERVATION` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLAIMOBSERVATION` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLAIMOBSERVATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CLLCTCNCLTIONBLCKDETAIL
-- ------------------------------------------------------

  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`PROCESSED` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`COUPON#` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`PAYMENTDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`PAYMENTMETHODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`CLLCTCNCLTIONBLOCKID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLCKDETAIL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CLLCTCNCLTIONBLOCK
-- ------------------------------------------------------

  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`PROCESSED` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`PROCESSEDTOTALVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`COUPONSPROCESS` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`REPORTEDTOTALVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`PAYMENTCOUPONS` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`BLOCKDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`COLLECTCONCILIATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CLLCTCNCLTIONBLOCK` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$COLLECTADDRESSCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` ADD CONSTRAINT `EIS$COLLECTADDRESSCHANGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` MODIFY (`REQUESTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$COLLECTCONCILIATION
-- ------------------------------------------------------

  ALTER TABLE `EIS$COLLECTCONCILIATION` ADD CONSTRAINT `EIS$COLLECTCONCILIATION_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`PROCESSED` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`PROCESSEDTOTALVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`COUPONSPROCESS` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`REPORTEDTOTALVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`PAYMENTCOUPONS` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`CONCILIATIONDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`COLLECTIONBRANCHID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTCONCILIATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$COLLECTIONBRANCH
-- ------------------------------------------------------

  ALTER TABLE `EIS$COLLECTIONBRANCH` ADD CONSTRAINT `EIS$COLLECTIONBRANCH_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$COLLECTIONBRANCH` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTIONBRANCH` MODIFY (`COLLECTIONORGANIZATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTIONBRANCH` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTIONBRANCH` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$COLLECTIONORGANIZATION
-- ------------------------------------------------------

  ALTER TABLE `EIS$COLLECTIONORGANIZATION` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTIONORGANIZATION` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$COLLECTIONORGANIZATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CONCEPT
-- ------------------------------------------------------

  ALTER TABLE `EIS$CONCEPT` ADD CONSTRAINT `EIS$CONCEPT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$CONCEPT` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CONCEPTATTENDEDINVOICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$CONCEPTATTENDEDINVOICE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`RATEOFCHANGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`SRVCCNCPTATTNDEDID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CONFIGPRODUCTSUPPLY
-- ------------------------------------------------------

  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` ADD CONSTRAINT `EIS$CONFIGPRODUCTSUPPLY_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` MODIFY (`QUANTITY` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` MODIFY (`PRODUCTSUPPLYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CUSTOMER
-- ------------------------------------------------------

  ALTER TABLE `EIS$CUSTOMER` ADD CONSTRAINT `EIS$CUSTOMER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`CUSTOMERTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`IDENTIFICATIONCODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`IDENTIFICATIONTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CUSTOMERSUBSCRIBER
-- ------------------------------------------------------

  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` ADD CONSTRAINT `EIS$CUSTOMERSUBSCRIBER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` MODIFY (`CUSTOMERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$CUSTOMERTYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$CUSTOMERTYPE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMERTYPE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$CUSTOMERTYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERRED
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERRED` MODIFY (`ISTHEREEXTRAPAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`DEFERREDSOURCETYPE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`SPREADINTERESTYPE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`INTERESRATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`DEFERREDINTERESTTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`CAPITALFIXEDPAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`AGREEPAYMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`RATEINITIALPAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`INITIALPAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`DEFERREDPLANDETAILID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`ISRECEIVEDINITIALPAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`PAYMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`RECEIVEDINTEREST` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`BALANCE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`PAYMENTFIRSTDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERRED` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDAMORTIZE
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDAMORTIZE` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDAMORTIZE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDAMORTIZE` MODIFY (`SHORTNAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDAMORTIZE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDAMORTIZE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDEXTRAPAYMENT
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDEXTRAPAYMENT` MODIFY (`ISPAYRECEIVED` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDEXTRAPAYMENT` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDEXTRAPAYMENT` MODIFY (`PAYMENTDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDEXTRAPAYMENT` MODIFY (`DEFERREDID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDEXTRAPAYMENT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDEXTRAPAYMENT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDINTERESTRATE
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDINTERESTRATE` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTRATE` MODIFY (`INTEREST` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTRATE` MODIFY (`DEFERREDINTERESTTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTRATE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTRATE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDINTERESTTYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDINTERESTTYPE` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTTYPE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTTYPE` MODIFY (`SHORTNAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTTYPE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDINTERESTTYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDMOVEMENT
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`PAYMENT` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`ISPAYMENTRECEIVED` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`INTERESTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`INTEREST` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`MOVEMENTDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`DEFERREDID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDMOVEMENT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDPLAN
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDPLAN` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLAN` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLAN` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLAN` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDPLANDETAIL
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`SPREADMAX` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`SPREADMIN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`INTERESTMAXPRCNTGE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`INTERESTMINPRCNTGE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`INTERESTTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`DEFERREDAMORTIZEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`EXTRAPAYAFTERPAY` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`EXTRAPAYMAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`MAXEXTRAPAYMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`MAXPAYMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`MINPAYMENTS` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`INITIALPAYMAXPRCNTGE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`INITIALPAYMINPRCNTGE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`DEFERREDPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDPLANDETAIL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DEFERREDSUPPORT
-- ------------------------------------------------------

  ALTER TABLE `EIS$DEFERREDSUPPORT` MODIFY (`PRCNTGEOVERDFRRED` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDSUPPORT` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDSUPPORT` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDSUPPORT` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDSUPPORT` MODIFY (`DEFERREDID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDSUPPORT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DEFERREDSUPPORT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENT_
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`DOCUMENTTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`ACCOUNTBALANCEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENT_` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`ACCOUNTBALANCEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_0001
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_0001_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0001` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_0002
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_0002_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0002` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_0003
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_0003_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0003` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_0004
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_0004_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0004` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_0005
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_0005_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0005` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_0006
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_0006_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_0006` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTDETAIL_OVFLW
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` ADD CONSTRAINT `EIS$DOCUMENTDETAIL_OVFLW_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`DISCOUNTVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`TAXVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`SIGN` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`MONEYVALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`TAXPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`OPERATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`FORMULAID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`BILLINGPLANID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`ACCOUNTINGDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`MOVEMENTPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`SERVICEUSERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`DOCUMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTDETAIL_OVFLW` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$DOCUMENTTYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTTYPE` ADD CONSTRAINT `EIS$DOCUMENTTYPE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$DOCUMENTTYPE` MODIFY (`SHORTNAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTTYPE` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTTYPE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$DOCUMENTTYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$FORMULA
-- ------------------------------------------------------

  ALTER TABLE `EIS$FORMULA` ADD CONSTRAINT `EIS$FORMULA_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$FORMULA` MODIFY (`FORMULA` NOT NULL ENABLE)
  ALTER TABLE `EIS$FORMULA` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$FORMULA` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$GEOLOCATION
-- ------------------------------------------------------

  ALTER TABLE `EIS$GEOLOCATION` ADD CONSTRAINT `EIS$GEOLOCATION_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$GEOLOCATION` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$GEOLOCATION` MODIFY (`CITYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$GEOLOCATION` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$GEOLOCATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$MASTERSTORAGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$MASTERSTORAGE` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `EIS$MASTERSTORAGE` MODIFY (`BILLPERIODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$MASTERSTORAGE` MODIFY (`BILLCYCLEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$MASTERSTORAGE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$MASTERSTORAGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$MASTERSTORAGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$OPERATION
-- ------------------------------------------------------

  ALTER TABLE `EIS$OPERATION` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$OPERATION` MODIFY (`SHORTNAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$OPERATION` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$OPERATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$PAYMENT
-- ------------------------------------------------------

  ALTER TABLE `EIS$PAYMENT` MODIFY (`CREATEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`MONEYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`PAYMENTDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`PAYMENTMETHODID` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`ACCOUNTCOLLECTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`CLLCTCNCLTIONBLCKDETAILID` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$PAYMENTMETHOD
-- ------------------------------------------------------

  ALTER TABLE `EIS$PAYMENTMETHOD` ADD CONSTRAINT `EIS$PAYMENTMETHOD_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$PAYMENTMETHOD` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENTMETHOD` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$PAYMENTMETHOD` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$PRODUCTSUPPLY
-- ------------------------------------------------------

  ALTER TABLE `EIS$PRODUCTSUPPLY` ADD CONSTRAINT `EIS$PRODUCTSUPPLY_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$PRODUCTSUPPLY` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$PRODUCTSUPPLY` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$PRODUCTSUPPLY` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$REASONSUSPEND
-- ------------------------------------------------------

  ALTER TABLE `EIS$REASONSUSPEND` ADD CONSTRAINT `EIS$REASONSUSPEND_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$REASONSUSPEND` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$REASONSUSPEND` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$REASONSUSPEND` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REASONSUSPEND` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$RECHARGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$RECHARGE` ADD CONSTRAINT `EIS$RECHARGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$RECHARGE` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGE` MODIFY (`DAYS` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGE` MODIFY (`APLICATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGE` MODIFY (`RECHARGEPERCENTAGEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGE` MODIFY (`ACCOUNTBALANCEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$RECHARGEPERCENTAGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$RECHARGEPERCENTAGE` ADD CONSTRAINT `EIS$RECHARGEPERCENTAGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$RECHARGEPERCENTAGE` MODIFY (`INITIALDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGEPERCENTAGE` MODIFY (`PERCENTAGE` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGEPERCENTAGE` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGEPERCENTAGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$RECHARGEPERCENTAGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$REFERENCEADDRESS
-- ------------------------------------------------------

  ALTER TABLE `EIS$REFERENCEADDRESS` MODIFY (`GEOLOCATIONID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REFERENCEADDRESS` MODIFY (`ADDRESSTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REFERENCEADDRESS` MODIFY (`ADDRESSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REFERENCEADDRESS` MODIFY (`REFERENCEOBJECTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REFERENCEADDRESS` MODIFY (`REFERENCEOBJECT` NOT NULL ENABLE)
  ALTER TABLE `EIS$REFERENCEADDRESS` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REFERENCEADDRESS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$REQUEST
-- ------------------------------------------------------

  ALTER TABLE `EIS$REQUEST` ADD CONSTRAINT `EIS$REQUEST_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$REQUEST` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REQUEST` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$REQUEST` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REQUEST` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REQUEST` MODIFY (`REQUESTTYPE` NOT NULL ENABLE)
  ALTER TABLE `EIS$REQUEST` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$REQUEST` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$REQUEST` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SALESMAN
-- ------------------------------------------------------

  ALTER TABLE `EIS$SALESMAN` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SALESMAN` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `EIS$SALESMAN` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SALESMAN` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SALESMAN` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SALESMAN` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SALESMAN` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SBSCRBERSRVCEACTIVATIONLOG
-- ------------------------------------------------------

  ALTER TABLE `EIS$SBSCRBERSRVCEACTIVATIONLOG` ADD CONSTRAINT `EIS$SBSCRBERSRVCEACTIVATIONLOG` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SBSCRBERSRVCEACTIVATIONLOG` MODIFY (`SUSPENDEDDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SBSCRBERSRVCEACTIVATIONLOG` MODIFY (`ACTIVATIONDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SBSCRBERSRVCEACTIVATIONLOG` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SBSCRBERSRVCEACTIVATIONLOG` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SBSCRBRSRVCRSNSUSPEND
-- ------------------------------------------------------

  ALTER TABLE `EIS$SBSCRBRSRVCRSNSUSPEND` ADD CONSTRAINT `EIS$SBSCRBRSRVCRSNSUSPEND_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SBSCRBRSRVCRSNSUSPEND` MODIFY (`REASONSUSPENDID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SBSCRBRSRVCRSNSUSPEND` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SBSCRBRSRVCRSNSUSPEND` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SBSCRBRSRVCRSNSUSPEND` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SERVICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICE` ADD CONSTRAINT `EIS$SERVICE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SERVICE` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICE` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICE` MODIFY (`SERVICETYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SERVICECOMPOSITION
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICECOMPOSITION` ADD CONSTRAINT `EIS$SERVICECOMPOSITION_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SERVICECOMPOSITION` MODIFY (`INVOICEINSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECOMPOSITION` MODIFY (`COMPONENTSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECOMPOSITION` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECOMPOSITION` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECOMPOSITION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SERVICECONCEPT
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICECONCEPT` MODIFY (`TAXTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECONCEPT` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECONCEPT` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECONCEPT` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECONCEPT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SERVICECONCEPTATTENDED
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICECONCEPTATTENDED` ADD CONSTRAINT `EIS$SERVICECONCEPTATTENDED_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SERVICECONCEPTATTENDED` MODIFY (`SERVICECONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECONCEPTATTENDED` MODIFY (`INVOICESERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECONCEPTATTENDED` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICECONCEPTATTENDED` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SERVICEITEM4SALE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICEITEM4SALE` MODIFY (`CONCEPTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEITEM4SALE` MODIFY (`VALUE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEITEM4SALE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEITEM4SALE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEITEM4SALE` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEITEM4SALE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEITEM4SALE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SERVICETYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICETYPE` ADD CONSTRAINT `EIS$SERVICETYPE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SERVICETYPE` MODIFY (`ICONOFILENAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICETYPE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICETYPE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICETYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SERVICEUSER
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICEUSER` ADD CONSTRAINT `EIS$SERVICEUSER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SERVICEUSER` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEUSER` MODIFY (`IDENTIFICATIONCODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEUSER` MODIFY (`IDENTIFICATIONTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEUSER` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEUSER` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SERVICEUSER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SUBSCRIBER
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBER` ADD CONSTRAINT `EIS$SUBSCRIBER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SUBSCRIBER` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBER` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBER` MODIFY (`IDENTIFICATIONCODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBER` MODIFY (`IDENTIFICATIONTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBER` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBER` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SUBSCRIBERCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHANGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` MODIFY (`REQUESTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SUBSCRIBERSERVICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBERSERVICE` ADD CONSTRAINT `EIS$SUBSCRIBERSERVICE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` MODIFY (`INVCEINSBSCRBERSRVCEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$SUBSCRIBERSERVICECHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERSERVICECHANGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` MODIFY (`REQUESTID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$TAXPERCENTAGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$TAXPERCENTAGE` ADD CONSTRAINT `EIS$TAXPERCENTAGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `EIS$TAXPERCENTAGE` MODIFY (`CREATEDATE` NOT NULL ENABLE)
  ALTER TABLE `EIS$TAXPERCENTAGE` MODIFY (`PERCENTAGE` NOT NULL ENABLE)
  ALTER TABLE `EIS$TAXPERCENTAGE` MODIFY (`TAXTYPEID` NOT NULL ENABLE)
  ALTER TABLE `EIS$TAXPERCENTAGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$TAXPERCENTAGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$TAXTYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$TAXTYPE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `EIS$TAXTYPE` MODIFY (`SHORTNAME` NOT NULL ENABLE)
  ALTER TABLE `EIS$TAXTYPE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$TAXTYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table EIS$TRIBUTARYSUBSCRIBERTYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$TRIBUTARYSUBSCRIBERTYPE` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `EIS$TRIBUTARYSUBSCRIBERTYPE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `EIS$TRIBUTARYSUBSCRIBERTYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$ACCOUNTCOLLECT
-- ------------------------------------------------------

  ALTER TABLE `EIS$ACCOUNTCOLLECT` ADD CONSTRAINT `EIS$ACCNTCLLCTCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$ACCOUNTCOLLECT` ADD CONSTRAINT `EIS$ACCNTCLLCTMONEY_F` FOREIGN KEY (`MONEYID`)
	  REFERENCES `EBS$MONEY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$ADDRESSCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$ADDRESSCHANGE` ADD CONSTRAINT `EIS$ADDRESSCHANGECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$ADDRESSCHANGE` ADD CONSTRAINT `EIS$ADDRESSCHANGEGEOLO_F` FOREIGN KEY (`GEOLOCATIONID`)
	  REFERENCES `EIS$GEOLOCATION` (`ID`);
  ALTER TABLE `EIS$ADDRESSCHANGE` ADD CONSTRAINT `EIS$ADDRESSCHANGEREQUEST_F` FOREIGN KEY (`REQUESTID`)
	  REFERENCES `EIS$REQUEST` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$AGREECOLLECTADDRESS
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREECOLLECTADDRESS` ADD CONSTRAINT `EIS$AGREECLLCTADDRCLLCTBRNCH_F` FOREIGN KEY (`COLLECTADDRESSREFERENCE`)
	  REFERENCES `EIS$COLLECTIONBRANCH` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$AGREEMENTSERVICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENTSERVICE` ADD CONSTRAINT `EIS$AGREESRVCECOMPANY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$AGREEMENTSERVICE` ADD CONSTRAINT `EIS$AGREESRVCESBSCRBERSRVCE_F` FOREIGN KEY (`SUBSCRIBERSERVICEID`)
	  REFERENCES `EIS$SUBSCRIBERSERVICE` (`ID`);
  ALTER TABLE `EIS$AGREEMENTSERVICE` ADD CONSTRAINT `EIS$AGREESRVCESRVCEUSR_F` FOREIGN KEY (`SERVICEUSERID`)
	  REFERENCES `EIS$SERVICEUSER` (`ID`);
  ALTER TABLE `EIS$AGREEMENTSERVICE` ADD CONSTRAINT `EIS$AGREESRVCESRVCE_F` FOREIGN KEY (`SERVICEID`)
	  REFERENCES `EIS$SERVICE` (`ID`);
  ALTER TABLE `EIS$AGREEMENTSERVICE` ADD CONSTRAINT `EIS$AGREESRVCEUSERPAY_F` FOREIGN KEY (`USERPAYMENTID`)
	  REFERENCES `EIS$SERVICEUSER` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$AGREEMENTSERVICEUSER
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` ADD CONSTRAINT `EIS$AGREESRVCEUSRAGREESRVCE_F` FOREIGN KEY (`AGREEMENTSERVICEID`)
	  REFERENCES `EIS$AGREEMENTSERVICE` (`ID`);
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` ADD CONSTRAINT `EIS$AGREESRVCEUSRCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` ADD CONSTRAINT `EIS$AGREESRVCEUSRSRVCEUSR_F` FOREIGN KEY (`SERVICEUSERID`)
	  REFERENCES `EIS$SERVICEUSER` (`ID`);
  ALTER TABLE `EIS$AGREEMENTSERVICEUSER` ADD CONSTRAINT `EIS$AGREESRVCEUSRUSRPAY_F` FOREIGN KEY (`USERPAYMENTID`)
	  REFERENCES `EIS$SERVICEUSER` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$AGREEMENTUSER
-- ------------------------------------------------------

  ALTER TABLE `EIS$AGREEMENTUSER` ADD CONSTRAINT `EIS$AGREEUSERAGREE_F` FOREIGN KEY (`AGREEMENTID`)
	  REFERENCES `EIS$AGREEMENT` (`ID`);
  ALTER TABLE `EIS$AGREEMENTUSER` ADD CONSTRAINT `EIS$AGREEUSERCOMPANY` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$AGREEMENTUSER` ADD CONSTRAINT `EIS$AGREEUSERPAYUSER_F` FOREIGN KEY (`USERPAYMENTID`)
	  REFERENCES `EIS$SERVICEUSER` (`ID`);
  ALTER TABLE `EIS$AGREEMENTUSER` ADD CONSTRAINT `EIS$AGREEUSERSRVCEUSER_F` FOREIGN KEY (`SERVICEUSERID`)
	  REFERENCES `EIS$SERVICEUSER` (`ID`);
  ALTER TABLE `EIS$AGREEMENTUSER` ADD CONSTRAINT `EIS$AGREEUSERSTATUS_F` FOREIGN KEY (`STATUSID`)
	  REFERENCES `EBS$STATUS` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$BILLCYCLE
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLCYCLE` ADD CONSTRAINT `EIS$BILLCYCLECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$BILLPERIOD
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLPERIOD` ADD CONSTRAINT `EIS$BILLPERIODBILLCYCLE_F` FOREIGN KEY (`BILLCYCLEID`)
	  REFERENCES `EIS$BILLCYCLE` (`ID`);
  ALTER TABLE `EIS$BILLPERIOD` ADD CONSTRAINT `EIS$BILLPERIODCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$BILLPLANCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLPLANCHANGE` ADD CONSTRAINT `EIS$BILLPLANCHANGEAGREEPREV_F` FOREIGN KEY (`PREVIOUSAGREEMENTID`)
	  REFERENCES `EIS$AGREEMENT` (`ID`);
  ALTER TABLE `EIS$BILLPLANCHANGE` ADD CONSTRAINT `EIS$BILLPLANCHANGEAGREE_F` FOREIGN KEY (`AGREEMENTID`)
	  REFERENCES `EIS$AGREEMENT` (`ID`);
  ALTER TABLE `EIS$BILLPLANCHANGE` ADD CONSTRAINT `EIS$BILLPLANCHANGEBILLPREV_F` FOREIGN KEY (`PREVIOUSBILLPLANID`)
	  REFERENCES `EIS$BILLPLAN` (`ID`);
  ALTER TABLE `EIS$BILLPLANCHANGE` ADD CONSTRAINT `EIS$BILLPLANCHANGEBILL_F` FOREIGN KEY (`BILLPLANID`)
	  REFERENCES `EIS$BILLPLAN` (`ID`);
  ALTER TABLE `EIS$BILLPLANCHANGE` ADD CONSTRAINT `EIS$BILLPLANCHANGECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$BILLPLANCHANGE` ADD CONSTRAINT `EIS$BILLPLANCHANGEREQUEST_F` FOREIGN KEY (`REQUESTID`)
	  REFERENCES `EIS$REQUEST` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$BILLSTATUS
-- ------------------------------------------------------

  ALTER TABLE `EIS$BILLSTATUS` ADD CONSTRAINT `EIS$BILLSTATUSCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$CLAIMOBSERVATION
-- ------------------------------------------------------

  ALTER TABLE `EIS$CLAIMOBSERVATION` ADD CONSTRAINT `EIS$CLAIMOBSERCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$COLLECTADDRESSCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` ADD CONSTRAINT `EIS$COLLECTADDRSSCHNGAGREE_F` FOREIGN KEY (`AGREEMENTID`)
	  REFERENCES `EIS$AGREEMENT` (`ID`);
  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` ADD CONSTRAINT `EIS$COLLECTADDRSSCHNGCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` ADD CONSTRAINT `EIS$COLLECTADDRSSCHNGE_F` FOREIGN KEY (`COLLECTADDRESSID`)
	  REFERENCES `EIS$AGREECOLLECTADDRESS` (`ID`);
  ALTER TABLE `EIS$COLLECTADDRESSCHANGE` ADD CONSTRAINT `EIS$COLLECTADDRSSCHNGRQST_F` FOREIGN KEY (`REQUESTID`)
	  REFERENCES `EIS$REQUEST` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$COLLECTCONCILIATION
-- ------------------------------------------------------

  ALTER TABLE `EIS$COLLECTCONCILIATION` ADD CONSTRAINT `EIS$CLLCTCNCLTIONCLLCTBRNCH_F` FOREIGN KEY (`COLLECTIONBRANCHID`)
	  REFERENCES `EIS$COLLECTIONBRANCH` (`ID`);
  ALTER TABLE `EIS$COLLECTCONCILIATION` ADD CONSTRAINT `EIS$CLLCTCNCLTIONCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$COLLECTCONCILIATION` ADD CONSTRAINT `EIS$CLLCTCNCLTIONMONEY_F` FOREIGN KEY (`MONEYID`)
	  REFERENCES `EBS$MONEY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$COLLECTIONBRANCH
-- ------------------------------------------------------

  ALTER TABLE `EIS$COLLECTIONBRANCH` ADD CONSTRAINT `EIS$CLLCTBRNCHCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$CONCEPT
-- ------------------------------------------------------

  ALTER TABLE `EIS$CONCEPT` ADD CONSTRAINT `EIS$CONCEPTCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$CONCEPTATTENDEDINVOICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICEAGRMNT_F` FOREIGN KEY (`AGREEMENTID`)
	  REFERENCES `EIS$AGREEMENT` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICEBLLCCLE_F` FOREIGN KEY (`BILLCYCLEID`)
	  REFERENCES `EIS$BILLCYCLE` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICEBLLPLN_F` FOREIGN KEY (`BILLINGPLANID`)
	  REFERENCES `EIS$BILLPLAN` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICEFRML_F` FOREIGN KEY (`FORMULAID`)
	  REFERENCES `EIS$FORMULA` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICEMNY_F` FOREIGN KEY (`MONEYID`)
	  REFERENCES `EBS$MONEY` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICEMVMNTPRD_F` FOREIGN KEY (`MOVEMENTPERIODID`)
	  REFERENCES `EIS$BILLPERIOD` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICESERVICE_F` FOREIGN KEY (`SERVICEID`)
	  REFERENCES `EIS$SERVICE` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTENDEDINVOICETXPRCNTG_F` FOREIGN KEY (`TAXPERCENTAGEID`)
	  REFERENCES `EIS$TAXPERCENTAGE` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$ATTNDDINVCSBSCRBRSRVC_F` FOREIGN KEY (`SUBSCRIBERSERVICEID`)
	  REFERENCES `EIS$SUBSCRIBERSERVICE` (`ID`);
  ALTER TABLE `EIS$CONCEPTATTENDEDINVOICE` ADD CONSTRAINT `EIS$INVOICESRVCCNCPTATTNDED_F` FOREIGN KEY (`SRVCCNCPTATTNDEDID`)
	  REFERENCES `EIS$SERVICECONCEPTATTENDED` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$CONFIGPRODUCTSUPPLY
-- ------------------------------------------------------

  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` ADD CONSTRAINT `EIS$CNFGPRDCTSPPLYCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` ADD CONSTRAINT `EIS$CNFGPRDCTSPPLYPRDCTSPPLY_F` FOREIGN KEY (`PRODUCTSUPPLYID`)
	  REFERENCES `EIS$PRODUCTSUPPLY` (`ID`);
  ALTER TABLE `EIS$CONFIGPRODUCTSUPPLY` ADD CONSTRAINT `EIS$CNFGPRDCTSPPLYSRVCE_F` FOREIGN KEY (`SERVICEID`)
	  REFERENCES `EIS$SERVICE` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$CUSTOMER
-- ------------------------------------------------------

  ALTER TABLE `EIS$CUSTOMER` ADD CONSTRAINT `EIS$CUSTOMERCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$CUSTOMER` ADD CONSTRAINT `EIS$CUSTOMERIDNTFCTIONTYPE_F` FOREIGN KEY (`IDENTIFICATIONTYPEID`)
	  REFERENCES `EBS$IDENTIFICATIONTYPE` (`ID`);
  ALTER TABLE `EIS$CUSTOMER` ADD CONSTRAINT `EIS$CUSTOMERLEAFNODE_F` FOREIGN KEY (`LEAFNODEID`)
	  REFERENCES `EIS$CUSTOMER` (`ID`);
  ALTER TABLE `EIS$CUSTOMER` ADD CONSTRAINT `EIS$CUSTOMERROOTNODE_F` FOREIGN KEY (`ROOTNODEID`)
	  REFERENCES `EIS$CUSTOMER` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$CUSTOMERSUBSCRIBER
-- ------------------------------------------------------

  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` ADD CONSTRAINT `EIS$CSTMERSBSCRBERCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` ADD CONSTRAINT `EIS$CSTMERSBSCRBERCUSTOMER_F` FOREIGN KEY (`CUSTOMERID`)
	  REFERENCES `EIS$CUSTOMER` (`ID`);
  ALTER TABLE `EIS$CUSTOMERSUBSCRIBER` ADD CONSTRAINT `EIS$CSTMERSBSCRBERSBSCRBER_F` FOREIGN KEY (`SUBSCRIBERID`)
	  REFERENCES `EIS$SUBSCRIBER` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$CUSTOMERTYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$CUSTOMERTYPE` ADD CONSTRAINT `EIS$CSTMERTYPECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$DOCUMENTTYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$DOCUMENTTYPE` ADD CONSTRAINT `EIS$DCMENTTYPECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$PAYMENTMETHOD
-- ------------------------------------------------------

  ALTER TABLE `EIS$PAYMENTMETHOD` ADD CONSTRAINT `EIS$PAYMETHODCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$PRODUCTSUPPLY
-- ------------------------------------------------------

  ALTER TABLE `EIS$PRODUCTSUPPLY` ADD CONSTRAINT `EIS$PRDCTSPPLYCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$REASONSUSPEND
-- ------------------------------------------------------

  ALTER TABLE `EIS$REASONSUSPEND` ADD CONSTRAINT `EIS$REASONSUSPENDCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$REQUEST
-- ------------------------------------------------------

  ALTER TABLE `EIS$REQUEST` ADD CONSTRAINT `EIS$REQUESTCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$REQUEST` ADD CONSTRAINT `EIS$REQUESTSTATUS_F` FOREIGN KEY (`STATUSID`)
	  REFERENCES `EBS$STATUS` (`ID`);
  ALTER TABLE `EIS$REQUEST` ADD CONSTRAINT `EIS$REQUESTSUBSCRIBER_F` FOREIGN KEY (`SUBSCRIBERID`)
	  REFERENCES `EIS$SUBSCRIBER` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SERVICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICE` ADD CONSTRAINT `EIS$SRVCECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$SERVICE` ADD CONSTRAINT `EIS$SRVCESRVCETYPE_F` FOREIGN KEY (`SERVICETYPEID`)
	  REFERENCES `EIS$SERVICETYPE` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SERVICECOMPOSITION
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICECOMPOSITION` ADD CONSTRAINT `EIS$SRVCECMPSTIONCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$SERVICECOMPOSITION` ADD CONSTRAINT `EIS$SRVCECMPSTIONCOMPONENT_F` FOREIGN KEY (`COMPONENTSERVICEID`)
	  REFERENCES `EIS$SERVICE` (`ID`);
  ALTER TABLE `EIS$SERVICECOMPOSITION` ADD CONSTRAINT `EIS$SRVCECMPSTIONINVOICEIN_F` FOREIGN KEY (`INVOICEINSERVICEID`)
	  REFERENCES `EIS$SERVICE` (`ID`);
  ALTER TABLE `EIS$SERVICECOMPOSITION` ADD CONSTRAINT `EIS$SRVCECMPSTIONSRVCE_F` FOREIGN KEY (`SERVICEID`)
	  REFERENCES `EIS$SERVICE` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SERVICECONCEPTATTENDED
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICECONCEPTATTENDED` ADD CONSTRAINT `EIS$SRVCCNCPTATTENDEDCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SERVICETYPE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICETYPE` ADD CONSTRAINT `EIS$SRVCETYPECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SERVICEUSER
-- ------------------------------------------------------

  ALTER TABLE `EIS$SERVICEUSER` ADD CONSTRAINT `EIS$SRVCEUSRCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$SERVICEUSER` ADD CONSTRAINT `EIS$SRVCEUSRIDNTFCTIONTYPE_F` FOREIGN KEY (`IDENTIFICATIONTYPEID`)
	  REFERENCES `EBS$IDENTIFICATIONTYPE` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SUBSCRIBER
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBER` ADD CONSTRAINT `EIS$SBSCRBERCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBER` ADD CONSTRAINT `EIS$SBSCRBERIDNTFCTIONTYPE_F` FOREIGN KEY (`IDENTIFICATIONTYPEID`)
	  REFERENCES `EBS$IDENTIFICATIONTYPE` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SUBSCRIBERCHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHANGECMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHANGEIDNTYPE_F` FOREIGN KEY (`IDENTIFICATIONTYPEID`)
	  REFERENCES `EBS$IDENTIFICATIONTYPE` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHANGEREQUEST_F` FOREIGN KEY (`REQUESTID`)
	  REFERENCES `EIS$REQUEST` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHNGAGREENW_F` FOREIGN KEY (`AGREEMENTID`)
	  REFERENCES `EIS$AGREEMENT` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHNGAGREE_F` FOREIGN KEY (`PREVIOUSAGREEMENTID`)
	  REFERENCES `EIS$AGREEMENT` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHNGSBSCRBNW_F` FOREIGN KEY (`SUBSCRIBERID`)
	  REFERENCES `EIS$SUBSCRIBER` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERCHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERCHNGSBSCRB_F` FOREIGN KEY (`PREVIOUSSUBSCRIBERID`)
	  REFERENCES `EIS$SUBSCRIBER` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SUBSCRIBERSERVICE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBERSERVICE` ADD CONSTRAINT `EIS$AGREECLLCTADDRCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` ADD CONSTRAINT `EIS$SBSCRBERSRVCEINVOICEIN_F` FOREIGN KEY (`INVCEINSBSCRBERSRVCEID`)
	  REFERENCES `EIS$SUBSCRIBERSERVICE` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` ADD CONSTRAINT `EIS$SBSCRBERSRVCESBSCRBER_F` FOREIGN KEY (`SUBSCRIBERID`)
	  REFERENCES `EIS$SUBSCRIBER` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERSERVICE` ADD CONSTRAINT `EIS$SBSCRBERSRVCESRVCE_F` FOREIGN KEY (`SERVICEID`)
	  REFERENCES `EIS$SERVICE` (`ID`);
-- ------------------------------------------------------
--  Ref Constraints for Table EIS$SUBSCRIBERSERVICECHANGE
-- ------------------------------------------------------

  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` ADD CONSTRAINT `EIS$SBSCRBRSRVCCHNGREQUEST_F` FOREIGN KEY (`REQUESTID`)
	  REFERENCES `EIS$REQUEST` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` ADD CONSTRAINT `EIS$SBSCRBRSRVCCHNGSBSCRNW_F` FOREIGN KEY (`SUBSCRIBERSERVICEID`)
	  REFERENCES `EIS$SUBSCRIBERSERVICE` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERSRVCCHNGCMPNY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`);
  ALTER TABLE `EIS$SUBSCRIBERSERVICECHANGE` ADD CONSTRAINT `EIS$SUBSCRIBERSRVCCHNGSBSCR_F` FOREIGN KEY (`PREVIOUSSUBSCRIBERSERVICEID`)
	  REFERENCES `EIS$SUBSCRIBERSERVICE` (`ID`);

