
  ALTER TABLE `BNK$ACCOUNTBALANCE_` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ACCOUNTBALANCE_0001
-- ------------------------------------------------------

  ALTER TABLE `BNK$ACCOUNTBALANCE_0001` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_0001_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0001` MODIFY (`PRINTCLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0001` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0001` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0001` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0001` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0001` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ACCOUNTBALANCE_0002
-- ------------------------------------------------------

  ALTER TABLE `BNK$ACCOUNTBALANCE_0002` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_0002_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0002` MODIFY (`PRINTCLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0002` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0002` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0002` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0002` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0002` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ACCOUNTBALANCE_0003
-- ------------------------------------------------------

  ALTER TABLE `BNK$ACCOUNTBALANCE_0003` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_0003_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0003` MODIFY (`PRINTCLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0003` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0003` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0003` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0003` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0003` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ACCOUNTBALANCE_0004
-- ------------------------------------------------------

  ALTER TABLE `BNK$ACCOUNTBALANCE_0004` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_0004_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0004` MODIFY (`PRINTCLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0004` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0004` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0004` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0004` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0004` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ACCOUNTBALANCE_0005
-- ------------------------------------------------------

  ALTER TABLE `BNK$ACCOUNTBALANCE_0005` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_0005_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0005` MODIFY (`PRINTCLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0005` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0005` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0005` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0005` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0005` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ACCOUNTBALANCE_0006
-- ------------------------------------------------------

  ALTER TABLE `BNK$ACCOUNTBALANCE_0006` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_0006_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0006` MODIFY (`PRINTCLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0006` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0006` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0006` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0006` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_0006` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ACCOUNTBALANCE_OVFLW
-- ------------------------------------------------------

  ALTER TABLE `BNK$ACCOUNTBALANCE_OVFLW` ADD CONSTRAINT `BNK$ACCOUNTBALANCE_OVFLW_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ACCOUNTBALANCE_OVFLW` MODIFY (`PRINTCLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_OVFLW` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_OVFLW` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_OVFLW` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_OVFLW` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ACCOUNTBALANCE_OVFLW` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_0001
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0001` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_0001_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0001` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0001` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_0002
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0002` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_0002_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0002` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0002` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_0003
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0003` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_0003_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0003` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0003` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_0004
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0004` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_0004_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0004` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0004` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_0005
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0005` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_0005_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0005` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0005` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_0006
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0006` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_0006_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0006` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_0006` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ADDTNALDCMENTDTIL_OVFLW
-- ------------------------------------------------------

  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_OVFLW` ADD CONSTRAINT `BNK$ADDTNALDCMENTDTIL_OVFLW_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_OVFLW` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$ADDTNALDCMENTDTIL_OVFLW` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$AGREEMENTSERVICE
-- ------------------------------------------------------

  ALTER TABLE `BNK$AGREEMENTSERVICE` ADD CONSTRAINT `BNK$AGREEMENTSERVICE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$AGREEMENTSERVICE` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$AGREEMENTSERVICE` MODIFY (`AGREEMENTSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$AGREEMENTSERVICE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$AGREESERVICECOLLECTADDRESS
-- ------------------------------------------------------

  ALTER TABLE `BNK$AGREESERVICECOLLECTADDRESS` MODIFY (`COLLECTADDRESS` NOT NULL ENABLE)
  ALTER TABLE `BNK$AGREESERVICECOLLECTADDRESS` MODIFY (`COLLECTADDRESSTYPEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$AGREESERVICECOLLECTADDRESS` MODIFY (`AGREEMENTSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$AGREESERVICECOLLECTADDRESS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$APPLICATION
-- ------------------------------------------------------

  ALTER TABLE `BNK$APPLICATION` ADD CONSTRAINT `BNK$APPLICATION_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$APPLICATION` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$APPLICATION` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$APPLICATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CHANNEL
-- ------------------------------------------------------

  ALTER TABLE `BNK$CHANNEL` ADD CONSTRAINT `BNK$CHANNEL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CHANNEL` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$CHANNEL` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$CHANNEL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CITYSTORE
-- ------------------------------------------------------

  ALTER TABLE `BNK$CITYSTORE` ADD CONSTRAINT `BNK$CITYSTORE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CITYSTORE` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `BNK$CITYSTORE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CLOSEPERIOD
-- ------------------------------------------------------

  ALTER TABLE `BNK$CLOSEPERIOD` ADD CONSTRAINT `BNK$CLOSEPERIOD_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CLOSEPERIOD` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `BNK$CLOSEPERIOD` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$CLOSEPERIOD` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$CLOSEPERIOD` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$CLOSEPERIOD` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CLOSEPERIOD` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$COMPENSATION
-- ------------------------------------------------------

  ALTER TABLE `BNK$COMPENSATION` ADD CONSTRAINT `BNK$COMPENSATION_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$COMPENSATION` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$COMPENSATION` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$COMPENSATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CONTROLPROCESSDEPEND
-- ------------------------------------------------------

  ALTER TABLE `BNK$CONTROLPROCESSDEPEND` ADD CONSTRAINT `BNK$CONTROLPROCESSDEPEND_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CONTROLPROCESSDEPEND` MODIFY (`EXECUTEDDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$CONTROLPROCESSDEPEND` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CONTROLPROCESSDEPEND` MODIFY (`PROCESSDEPENDID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CONTROLPROCESSDEPEND` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CREDITCARDFIX2SEG
-- ------------------------------------------------------

  ALTER TABLE `BNK$CREDITCARDFIX2SEG` ADD CONSTRAINT `CREDITCARDFIX2SEG_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG` MODIFY (`PRINTINDICATOR` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG` MODIFY (`SEGMENTPROGRAM` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG` MODIFY (`LETTERACCOUNT` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG` MODIFY (`PRODUCT` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CREDITCARDFIX2SEG_BCK
-- ------------------------------------------------------

  ALTER TABLE `BNK$CREDITCARDFIX2SEG_BCK` MODIFY (`PRINTINDICATOR` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG_BCK` MODIFY (`SEGMENTPROGRAM` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG_BCK` MODIFY (`LETTERACCOUNT` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG_BCK` MODIFY (`PRODUCT` NOT NULL ENABLE)
  ALTER TABLE `BNK$CREDITCARDFIX2SEG_BCK` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CUSTOMER
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMER` ADD CONSTRAINT `BNK$CUSTOMER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CUSTOMER` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMER` MODIFY (`NAME` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMER` MODIFY (`IDENTIFICATIONCODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMER` MODIFY (`IDENTIFICATIONTYPEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMER` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMER` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CUSTOMERCOLLECTADDRESS
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMERCOLLECTADDRESS` ADD CONSTRAINT `BNK$CUSTOMERCOLLECTADDRESS_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CUSTOMERCOLLECTADDRESS` MODIFY (`COLLECTADDRESSTYPEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMERCOLLECTADDRESS` MODIFY (`CUSTOMERID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMERCOLLECTADDRESS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CUSTOMERFIX2PRN
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMERFIX2PRN` ADD CONSTRAINT `BNK$CUSTOMERFIX2PRN_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CUSTOMERFIX2PRN` MODIFY (`PRODUCT` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMERFIX2PRN` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CUSTOMERSUBSCRIBER
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMERSUBSCRIBER` ADD CONSTRAINT `BNK$CUSTOMERSUBSCRIBER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CUSTOMERSUBSCRIBER` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMERSUBSCRIBER` MODIFY (`CUSTOMERID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMERSUBSCRIBER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$CUSTOMERTYPE
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMERTYPE` ADD CONSTRAINT `BNK$CUSTOMERTYPE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$CUSTOMERTYPE` MODIFY (`CUSTOMERTYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMERTYPE` MODIFY (`SUBSCRIBERID` NOT NULL ENABLE)
  ALTER TABLE `BNK$CUSTOMERTYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DIRTYACCNTBLNCEBFRECLSE
-- ------------------------------------------------------

  ALTER TABLE `BNK$DIRTYACCNTBLNCEBFRECLSE` MODIFY (`CLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$DIRTYACCNTBLNCEBFRECLSE` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$DIRTYACCNTBLNCEBFRECLSE` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$DIRTYACCNTBLNCEBFRECLSE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$DIRTYACCNTBLNCEBFRECLSE` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DIRTYACCNTBLNCEBFRECLSE` MODIFY (`FILECONTROLID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_IK_` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_0001
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_0001` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_0001_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0001` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0001` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0001` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_0002
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_0002` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_0002_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0002` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0002` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0002` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_0003
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_0003` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_0003_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0003` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0003` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0003` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_0004
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_0004` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_0004_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0004` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0004` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0004` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_0005
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_0005` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_0005_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0005` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0005` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0005` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_0006
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_0006` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_0006_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0006` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0006` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_0006` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$DOCUMENTDETAIL_OVFLW
-- ------------------------------------------------------

  ALTER TABLE `BNK$DOCUMENTDETAIL_OVFLW` ADD CONSTRAINT `BNK$DOCUMENTDETAIL_OVFLW_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$DOCUMENTDETAIL_OVFLW` MODIFY (`AGREEMENTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_OVFLW` MODIFY (`DOCUMENTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$DOCUMENTDETAIL_OVFLW` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$ERRORNOTIFY
-- ------------------------------------------------------

  ALTER TABLE `BNK$ERRORNOTIFY` ADD CONSTRAINT `BNK$ERRORNOTIFY_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$ERRORNOTIFY` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$EXCEPTIONDATE
-- ------------------------------------------------------

  ALTER TABLE `BNK$EXCEPTIONDATE` ADD CONSTRAINT `BNK$EXCEPTIONDATE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$EXCEPTIONDATE` MODIFY (`EXCEPTIONDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$EXCEPTIONDATE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$FILECONTROL
-- ------------------------------------------------------

  ALTER TABLE `BNK$FILECONTROL` ADD CONSTRAINT `BNK$FILECONTROL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$FILECONTROL` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `BNK$FILECONTROL` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `BNK$FILECONTROL` MODIFY (`TRIES` NOT NULL ENABLE)
  ALTER TABLE `BNK$FILECONTROL` MODIFY (`FILESIZE` NOT NULL ENABLE)
  ALTER TABLE `BNK$FILECONTROL` MODIFY (`FILENAME` NOT NULL ENABLE)
  ALTER TABLE `BNK$FILECONTROL` MODIFY (`SERVICETYPEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$FILECONTROL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$FORCESTATEMENT
-- ------------------------------------------------------

  ALTER TABLE `BNK$FORCESTATEMENT` ADD CONSTRAINT `BNK$FORCESTATEMENT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$FORCESTATEMENT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$LOG4COLLECT
-- ------------------------------------------------------

  ALTER TABLE `BNK$LOG4COLLECT` ADD CONSTRAINT `BNK$LOG4COLLECT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$LOG4COLLECT` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$LOG4COLLECT` MODIFY (`FILECONTROLID` NOT NULL ENABLE)
  ALTER TABLE `BNK$LOG4COLLECT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$MARKEDPROGRAM
-- ------------------------------------------------------

  ALTER TABLE `BNK$MARKEDPROGRAM` ADD CONSTRAINT `BNK$MARKEDPROGRAM_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$MARKEDPROGRAM` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$MARKEDPROGRAM` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$MASTERSTORAGE
-- ------------------------------------------------------

  ALTER TABLE `BNK$MASTERSTORAGE` ADD CONSTRAINT `BNK$MASTERSTORAGE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$MASTERSTORAGE` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$MASTERSTORAGE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$MASTERSTORAGE` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `BNK$MASTERSTORAGE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$MASTERSTORAGEFILECONTROL
-- ------------------------------------------------------

  ALTER TABLE `BNK$MASTERSTORAGEFILECONTROL` ADD CONSTRAINT `BNK$MSTRSTRGEFILECNTRL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$MASTERSTORAGEFILECONTROL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$NOTES
-- ------------------------------------------------------

  ALTER TABLE `BNK$NOTES` ADD CONSTRAINT `BNK$NOTES_ID` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$NOTES` MODIFY (`PRINT` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`TOTALVALUE` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`CONCEPT` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`NATURE` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`TRANSACTIONDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`SECUENCE` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`OPERATION` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`ACCOUNTNUMBER` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`SUBSCRIBERSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`FILECONTROLID` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`COMPANYID` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTES` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$NOTESDETAIL
-- ------------------------------------------------------

  ALTER TABLE `BNK$NOTESDETAIL` ADD CONSTRAINT `BNK$NOTESDETAIL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$NOTESDETAIL` MODIFY (`DETAIL` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTESDETAIL` MODIFY (`LINE` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTESDETAIL` MODIFY (`SECUENCE` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTESDETAIL` MODIFY (`OPERATION` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTESDETAIL` MODIFY (`ACCOUNTNUMBER` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTESDETAIL` MODIFY (`FILECONTROLID` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTESDETAIL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$NOTETYPE
-- ------------------------------------------------------

  ALTER TABLE `BNK$NOTETYPE` ADD CONSTRAINT `BNK$NOTETYPE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$NOTETYPE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTETYPE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$NOTETYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$OBSTRUCT
-- ------------------------------------------------------

  ALTER TABLE `BNK$OBSTRUCT` ADD CONSTRAINT `BNK$OBSTRUCT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$OBSTRUCT` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$OBSTRUCT` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$OBSTRUCT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PDF
-- ------------------------------------------------------

  ALTER TABLE `BNK$PDF` ADD CONSTRAINT `BNK$PDF_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PDF` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDF` MODIFY (`EQUIPMENT` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDF` MODIFY (`GENERATEDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDF` MODIFY (`TECHNICALCODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDF` MODIFY (`PRODUCTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDF` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDF` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDF` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PDFCONFIGURATION
-- ------------------------------------------------------

  ALTER TABLE `BNK$PDFCONFIGURATION` ADD CONSTRAINT `BNK$PDFCONFIGURATION_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PDFCONFIGURATION` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PDFNOTPRINTING
-- ------------------------------------------------------

  ALTER TABLE `BNK$PDFNOTPRINTING` ADD CONSTRAINT `BNK$PDFNOTPRINTING_UX01` UNIQUE (`SERVICEID`, `PRODUCTID`, `YEAR`, `MONTH`, `CLOSETYPE`)
  ALTER TABLE `BNK$PDFNOTPRINTING` ADD CONSTRAINT `BNK$PDFNOTPRINTING_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PDFNOTPRINTING` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PDFSPOOL
-- ------------------------------------------------------

  ALTER TABLE `BNK$PDFSPOOL` ADD CONSTRAINT `BNK$PDFSPOOL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PDFSPOOL` MODIFY (`FILENAME` NOT NULL ENABLE)
  ALTER TABLE `BNK$PDFSPOOL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PHONETYPE
-- ------------------------------------------------------

  ALTER TABLE `BNK$PHONETYPE` ADD CONSTRAINT `BNK$PHONETYPE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PHONETYPE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$PHONETYPE` MODIFY (`PHONETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$PHONETYPE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PLACESTORE
-- ------------------------------------------------------

  ALTER TABLE `BNK$PLACESTORE` ADD CONSTRAINT `BNK$PLACESTORE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PLACESTORE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$PLACESTORE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PRINTDETAIL
-- ------------------------------------------------------

  ALTER TABLE `BNK$PRINTDETAIL` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$PRINTDETAIL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PROCESSDEPEND
-- ------------------------------------------------------

  ALTER TABLE `BNK$PROCESSDEPEND` ADD CONSTRAINT `BNK$PROCESSDEPEND_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PROCESSDEPEND` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `BNK$PROCESSDEPEND` MODIFY (`COMMAND` NOT NULL ENABLE)
  ALTER TABLE `BNK$PROCESSDEPEND` MODIFY (`EXECUTEDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$PROCESSDEPEND` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `BNK$PROCESSDEPEND` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PROCESSINSTANCE
-- ------------------------------------------------------

  ALTER TABLE `BNK$PROCESSINSTANCE` ADD CONSTRAINT `BNK$PROCESSINSTANCE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PROCESSINSTANCE` MODIFY (`PROCESSINSTANCEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$PROCESSINSTANCE` MODIFY (`PROCESSID` NOT NULL ENABLE)
  ALTER TABLE `BNK$PROCESSINSTANCE` MODIFY (`DATEPROCESSED` NOT NULL ENABLE)
  ALTER TABLE `BNK$PROCESSINSTANCE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PRODUCT
-- ------------------------------------------------------

  ALTER TABLE `BNK$PRODUCT` ADD CONSTRAINT `BNK$PRODUCT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PRODUCT` MODIFY (`SYSTEMCODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$PRODUCT` MODIFY (`APPLICATIONID` NOT NULL ENABLE)
  ALTER TABLE `BNK$PRODUCT` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$PRODUCT` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$PRODUCT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PRODUCTEBPRODUCT
-- ------------------------------------------------------

  ALTER TABLE `BNK$PRODUCTEBPRODUCT` ADD CONSTRAINT `BNK$PRODUCTEBPRODUCT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PRODUCTEBPRODUCT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$PRWSTATEMENT
-- ------------------------------------------------------

  ALTER TABLE `BNK$PRWSTATEMENT` ADD CONSTRAINT `BNK$PRWSTATEMENT_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$PRWSTATEMENT` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$QUERYDATA
-- ------------------------------------------------------

  ALTER TABLE `BNK$QUERYDATA` ADD CONSTRAINT `BNK$QUERYDATA_IK` PRIMARY KEY (`PROCESSID`, `ORDERDATA`)
  ALTER TABLE `BNK$QUERYDATA` MODIFY (`AGREEMENTSERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$QUERYDATA` MODIFY (`ORDERDATA` NOT NULL ENABLE)
  ALTER TABLE `BNK$QUERYDATA` MODIFY (`PROCESSID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$RESCHEDULINGPROCESS
-- ------------------------------------------------------

  ALTER TABLE `BNK$RESCHEDULINGPROCESS` ADD CONSTRAINT `BNK$RESCHEDULINGPROCESS_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$RESCHEDULINGPROCESS` MODIFY (`RESCHEDULINGUNTIL` NOT NULL ENABLE)
  ALTER TABLE `BNK$RESCHEDULINGPROCESS` MODIFY (`RESCHEDULINGEACH` NOT NULL ENABLE)
  ALTER TABLE `BNK$RESCHEDULINGPROCESS` MODIFY (`PROCESSDEPENDID` NOT NULL ENABLE)
  ALTER TABLE `BNK$RESCHEDULINGPROCESS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$RETURNCAUSE
-- ------------------------------------------------------

  ALTER TABLE `BNK$RETURNCAUSE` ADD CONSTRAINT `BNK$RETURNCAUSE_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$RETURNCAUSE` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$RETURNCAUSE` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$RETURNCAUSE` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$SENDDETAILPDF
-- ------------------------------------------------------

  ALTER TABLE `BNK$SENDDETAILPDF` ADD CONSTRAINT `BNK$SENDDETAILPDF_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$SENDDETAILPDF` MODIFY (`EXTRACTTYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDDETAILPDF` MODIFY (`SENDPDFID` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDDETAILPDF` MODIFY (`CLOSEDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDDETAILPDF` MODIFY (`PRODUCTID` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDDETAILPDF` MODIFY (`PRODUCTTYPEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDDETAILPDF` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$SENDPDF
-- ------------------------------------------------------

  ALTER TABLE `BNK$SENDPDF` ADD CONSTRAINT `BNK$SENDPDF_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$SENDPDF` MODIFY (`BANKTYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDPDF` MODIFY (`CLOSETYPE` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDPDF` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDPDF` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDPDF` MODIFY (`SECUENCE` NOT NULL ENABLE)
  ALTER TABLE `BNK$SENDPDF` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$STATUS
-- ------------------------------------------------------

  ALTER TABLE `BNK$STATUS` ADD CONSTRAINT `BNK$STATUS_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$STATUS` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$STATUS` MODIFY (`CODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$STATUS` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$STORELIST
-- ------------------------------------------------------

  ALTER TABLE `BNK$STORELIST` MODIFY (`DESCRIPTION` NOT NULL ENABLE)
  ALTER TABLE `BNK$STORELIST` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$TPLSERVICEPRINTDETAIL
-- ------------------------------------------------------

  ALTER TABLE `BNK$TPLSERVICEPRINTDETAIL` MODIFY (`PRINTORDER` NOT NULL ENABLE)
  ALTER TABLE `BNK$TPLSERVICEPRINTDETAIL` MODIFY (`PRINTBLOCK` NOT NULL ENABLE)
  ALTER TABLE `BNK$TPLSERVICEPRINTDETAIL` MODIFY (`PRINTDETAILID` NOT NULL ENABLE)
  ALTER TABLE `BNK$TPLSERVICEPRINTDETAIL` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$TPLSERVICEPRINTDETAIL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$USER
-- ------------------------------------------------------

  ALTER TABLE `BNK$USER` ADD CONSTRAINT `BNK$USER_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$USER` MODIFY (`MAIL` NOT NULL ENABLE)
  ALTER TABLE `BNK$USER` MODIFY (`USERID` NOT NULL ENABLE)
  ALTER TABLE `BNK$USER` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$WEBACCESSLOG
-- ------------------------------------------------------

  ALTER TABLE `BNK$WEBACCESSLOG` ADD CONSTRAINT `BNK$WEBACCESSLOG_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`FROMDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`STATUS` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`TECHNICALCODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`IDENTIFICATIONCODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`MONTH` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`YEAR` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`SERVICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOG` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$WEBACCESSLOGDETAIL
-- ------------------------------------------------------

  ALTER TABLE `BNK$WEBACCESSLOGDETAIL` MODIFY (`STATUSID` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOGDETAIL` MODIFY (`PATH` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOGDETAIL` MODIFY (`WEBACCESSLOGID` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBACCESSLOGDETAIL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Constraints for Table BNK$WEBOFFICEACCESSDETAIL
-- ------------------------------------------------------

  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` ADD CONSTRAINT `BNK$WEBOFFICEACCESSDETAIL_IK` PRIMARY KEY (`ID`)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`PAGES` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`IDENTIFICATIONTYPEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`TRANSACTIONSEQUENCE` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`TERMINALCODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`DAYFRAME` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`TRANSACTIONDATE` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`USERTRANSACTIONCODE` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`OFFICEID` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`WEBACCESSLOGID` NOT NULL ENABLE)
  ALTER TABLE `BNK$WEBOFFICEACCESSDETAIL` MODIFY (`ID` NOT NULL ENABLE)
-- ------------------------------------------------------
--  Ref Constraints for Table BNK$CUSTOMER
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMER` ADD CONSTRAINT `BNK$CUSTOMERCOMPANY_F` FOREIGN KEY (`COMPANYID`)
	  REFERENCES `EBS$COMPANY` (`ID`)
  ALTER TABLE `BNK$CUSTOMER` ADD CONSTRAINT `BNK$CUSTOMERIDENTIFICATION_F` FOREIGN KEY (`IDENTIFICATIONTYPEID`)
	  REFERENCES `EBS$IDENTIFICATIONTYPE` (`ID`)
-- ------------------------------------------------------
--  Ref Constraints for Table BNK$CUSTOMERSUBSCRIBER
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMERSUBSCRIBER` ADD CONSTRAINT `BNK$CUSTOMERSUBSCRIBERS_F` FOREIGN KEY (`SUBSCRIBERID`)
	  REFERENCES `EIS$SUBSCRIBER` (`ID`)
-- ------------------------------------------------------
--  Ref Constraints for Table BNK$CUSTOMERTYPE
-- ------------------------------------------------------

  ALTER TABLE `BNK$CUSTOMERTYPE` ADD CONSTRAINT `BNK$CUSTOMERTYPESUBSCRIBER_F` FOREIGN KEY (`SUBSCRIBERID`)
	  REFERENCES `EIS$SUBSCRIBER` (`ID`)
-- ------------------------------------------------------
--  Ref Constraints for Table BNK$FILECONTROL
-- ------------------------------------------------------

  ALTER TABLE `BNK$FILECONTROL` ADD CONSTRAINT `BNK$FILECONTROLSERVICE_F` FOREIGN KEY (`SERVICETYPEID`)
	  REFERENCES `EIS$SERVICETYPE` (`ID`)

