--------------------------------------------------------
-- Archivo creado  - jueves-febrero-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EWS$ACCOUNTBALANCE
--------------------------------------------------------

  CREATE TABLE "EWS$ACCOUNTBALANCE" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"CODE" VARCHAR2(16), 
	"AGREEMENTID" NUMBER, 
	"SERVICEID" NUMBER, 
	"SUBSCRIBERSERVICEID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"BILLCYCLEID" NUMBER, 
	"BILLPERIODID" NUMBER, 
	"YEAR" NUMBER(4,0), 
	"MONTH" NUMBER(2,0), 
	"CREATEDDATE" DATE, 
	"PAYMENTDATELIMIT" DATE, 
	"MONEYID" NUMBER, 
	"VALUE" NUMBER(18,2), 
	"BALANCE" NUMBER(18,2), 
	"BALANCE2AGREE" NUMBER(18,2), 
	"ADJUSTVALUE" NUMBER(18,5), 
	"BALANCEAGREEBEROFEBILL" NUMBER(18,2), 
	"BALANCEAGREEAFTERBILL" NUMBER(18,2), 
	"ROWC" NUMBER
   )
--------------------------------------------------------
--  DDL for Table EWS$AGREEMENT
--------------------------------------------------------

  CREATE TABLE "EWS$AGREEMENT" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"SUBSCRIBERID" NUMBER, 
	"BILLPLANID" NUMBER, 
	"BILLCYCLEID" NUMBER, 
	"MONEYID" NUMBER, 
	"BALANCE2COMPANY" NUMBER(18,2), 
	"BALANCE2AGREE" NUMBER(18,2), 
	"FROMDATE" DATE, 
	"TODATE" DATE, 
	"STATUSID" NUMBER, 
	"LASTBILLINGDATE" DATE, 
	"NEXTBILLINGDATE" DATE, 
	"BILLINGPERIODICITY" NUMBER, 
	"ROWC" NUMBER
   )
--------------------------------------------------------
--  DDL for Table EWS$AGREEMENTSERVICE
--------------------------------------------------------

  CREATE TABLE "EWS$AGREEMENTSERVICE" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"AGREEMENTID" NUMBER, 
	"SERVICEID" NUMBER, 
	"SUBSCRIBERSERVICEID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"BILLPLANID" NUMBER, 
	"PENDINGACCOUNTS" NUMBER, 
	"BALANCE2COMPANY" NUMBER(18,2), 
	"FROMDATE" DATE, 
	"TODATE" DATE, 
	"STATUSID" NUMBER, 
	"ACCOUNTBALANCEID" NUMBER, 
	"INVOICEDOCUMENTID" NUMBER, 
	"DEBITDOCUMENTID" NUMBER, 
	"CREDITDOCUMENTID" NUMBER, 
	"SBSCRBERSRVCESTATUSID" NUMBER, 
	"LASTACTIVATIONDATE" DATE, 
	"LASTSUSPENDEDDATE" DATE, 
	"LASTRATINGDATE" DATE, 
	"NEXTRATINGDATE" DATE, 
	"ROWC" NUMBER
   )
--------------------------------------------------------
--  DDL for Table EWS$AGREEMENTSERVICEUSER
--------------------------------------------------------

  CREATE TABLE "EWS$AGREEMENTSERVICEUSER" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"AGREEMENTSERVICEID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"PENDINGACCOUNTS" NUMBER(3,0), 
	"BALANCE2COMPANY" NUMBER(18,2), 
	"FROMDATE" DATE, 
	"TODATE" DATE, 
	"STATUSID" NUMBER, 
	"ROWC" NUMBER
   )
--------------------------------------------------------
--  DDL for Table EWS$AGREEMENTUSER
--------------------------------------------------------

  CREATE TABLE "EWS$AGREEMENTUSER" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"AGREEMENTID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"BALANCE2COMPANY" NUMBER(18,2), 
	"BALANCE2USER" NUMBER(18,2), 
	"FROMDATE" DATE, 
	"TODATE" DATE, 
	"STATUSID" NUMBER, 
	"ROWC" NUMBER
   )
--------------------------------------------------------
--  DDL for Table EWS$BNKACCOUNTBALANCE
--------------------------------------------------------

  CREATE TABLE "EWS$BNKACCOUNTBALANCE" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"ACCOUNTBALANCEID" NUMBER, 
	"CODE" VARCHAR2(16), 
	"AGREEMENTID" NUMBER, 
	"SERVICEID" NUMBER, 
	"SUBSCRIBERSERVICEID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"BILLCYCLEID" NUMBER, 
	"BILLPERIODID" NUMBER, 
	"MOVEMENTPERIODID" NUMBER, 
	"YEAR" NUMBER(4,0), 
	"MONTH" NUMBER(2,0), 
	"CREATEDDATE" DATE, 
	"PAYMENTDATELIMIT" DATE, 
	"MONEYID" NUMBER, 
	"VALUE" NUMBER(18,2), 
	"BALANCE" NUMBER(18,2), 
	"PAYMENTDATE" DATE, 
	"INSTALLMENTBALANCE2AGREE" NUMBER(18,2), 
	"PAYMENTS" NUMBER(18,2), 
	"CLAIMVALUE" NUMBER(18,2), 
	"CLAIMPAYMENTNONPAID" NUMBER(18,2), 
	"BALANCEAGREEBEROFEBILL" NUMBER(18,2), 
	"BALANCEAGREEAFTERBILL" NUMBER(18,2), 
	"PRINTDETAILID" NUMBER, 
	"TOTALMONTHUSE" NUMBER, 
	"CREDITSTATUS" NUMBER, 
	"CURRENTTAXES" NUMBER, 
	"MOORTAXES" NUMBER, 
	"LIFESECURITY" NUMBER, 
	"MANAGMENTQUOTE" NUMBER, 
	"TOTALPAYMENT" NUMBER, 
	"MINIMPAYMENT" NUMBER, 
	"MONTHYTAXES" NUMBER, 
	"MONTHYMOORTAXES" NUMBER, 
	"ANUALTAXES" NUMBER, 
	"ANUALMOORTAXES" NUMBER, 
	"LASTPERIODTAXES" NUMBER, 
	"DAYMOOR" NUMBER, 
	"LASTPAYMENTTAXES" NUMBER, 
	"LASTPERIODSECURITY" NUMBER, 
	"CREDITLINECODE" VARCHAR2(3), 
	"PRINT" VARCHAR2(1), 
	"MONTHSPOINT" NUMBER, 
	"ACUMULATEPOINT" NUMBER, 
	"MOORDATE" DATE, 
	"LETTERACCOUNT" NUMBER, 
	"OVERDRAFTAXES" NUMBER, 
	"SEIZUREVALUE" NUMBER, 
	"ACTUALBALANCE" NUMBER, 
	"AVERAGEBALANCE" NUMBER, 
	"MONTHDEBITS" NUMBER, 
	"MONTHCREDITS" NUMBER, 
	"DEBITVALUES" NUMBER, 
	"CREDITVALUES" NUMBER, 
	"LASTMONTHBALANCE" NUMBER, 
	"LASTDAYBALANCE" NUMBER, 
	"PAYMENTINDICATE" VARCHAR2(30), 
	"CURRENTTAXESCHAR" VARCHAR2(32), 
	"CURRENTINTCHAR" VARCHAR2(30), 
	"ROWC" NUMBER, 
	"SRCFILELINENO" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."OVERDRAFTAXES" IS 'Interes de sobregiro'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."SEIZUREVALUE" IS 'Valor de embargo'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."ACTUALBALANCE" IS 'Saldo actual'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."AVERAGEBALANCE" IS 'Saldo promedio'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."MONTHDEBITS" IS 'Numero de debito del mes'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."MONTHCREDITS" IS 'Numero de credito del mes'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."DEBITVALUES" IS 'Valor de debito'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."CREDITVALUES" IS 'Valor de credito'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."LASTMONTHBALANCE" IS 'Saldo mes anterior'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."LASTDAYBALANCE" IS 'Saldo dia anterior'
   COMMENT ON COLUMN "EWS$BNKACCOUNTBALANCE"."SRCFILELINENO" IS 'Numero linea archivo fuente'
--------------------------------------------------------
--  DDL for Table EWS$BNKADDTNALDCMENTDTIL
--------------------------------------------------------

  CREATE TABLE "EWS$BNKADDTNALDCMENTDTIL" 
   (	"ID" NUMBER, 
	"DOCUMENTDETAILID" NUMBER, 
	"DESCRIPTION" VARCHAR2(60), 
	"CREATEDSECUENCE" NUMBER, 
	"AGREEMENTID" NUMBER, 
	"ROWC" NUMBER, 
	"SRCFILELINENO" NUMBER, 
	"YEAR" NUMBER(4,0), 
	"MONTH" NUMBER(2,0), 
	"PRINTCLOSETYPE" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."ID" IS 'Codigo interno del sistema'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."DOCUMENTDETAILID" IS 'Id del movimiento relacionado'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."DESCRIPTION" IS 'Detalle adicional del movimiento'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."CREATEDSECUENCE" IS 'Orden de generacion de los detalles'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."AGREEMENTID" IS 'Codigo interno del Control de Archivos'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."SRCFILELINENO" IS 'Numero linea archivo fuente'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."YEAR" IS 'Año corte impresion extracto'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."MONTH" IS 'Mes corte impresion extractos'
   COMMENT ON COLUMN "EWS$BNKADDTNALDCMENTDTIL"."PRINTCLOSETYPE" IS 'Tipo corte impresion extractos'
--------------------------------------------------------
--  DDL for Table EWS$BNKAGREEMENTSERVICE
--------------------------------------------------------

  CREATE TABLE "EWS$BNKAGREEMENTSERVICE" 
   (	"ID" NUMBER, 
	"AGREEMENTSERVICEID" NUMBER, 
	"COMPANYID" NUMBER, 
	"AGREEMENTID" NUMBER, 
	"SERVICEID" NUMBER, 
	"SUBSCRIBERSERVICEID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"USERPAYMENTID" NUMBER, 
	"PENDINGACCOUNTS" NUMBER(3,0), 
	"BALANCE2COMPANY" NUMBER(18,2), 
	"CLAIMVALUE" NUMBER(18,2), 
	"CLAIMPAYMENTNONPAID" NUMBER(18,2), 
	"FROMDATE" DATE, 
	"TODATE" DATE, 
	"STATUSID" NUMBER, 
	"ACCOUNTBALANCEID" NUMBER, 
	"BILLPLANID" NUMBER, 
	"LASTRATINGDATE" DATE, 
	"NEXTRATINGDATE" DATE, 
	"FRQUNCYGNRTEACCNT" VARCHAR2(1), 
	"NOTEDELIVERY" VARCHAR2(1), 
	"MAGNETICSHIP" VARCHAR2(1), 
	"BALANCE" NUMBER, 
	"BALANCEAVERAGE" NUMBER, 
	"LASTDAYBALANCE" NUMBER, 
	"MONTHDEBITS" NUMBER, 
	"MONTHCREDITS" NUMBER, 
	"DEBTISVALUE" NUMBER, 
	"CREDITVALUES" NUMBER, 
	"OVERDRAFTTAX" NUMBER, 
	"PRINTACCNT" VARCHAR2(1), 
	"CARDSTATUS" VARCHAR2(2), 
	"LOOKSTATUS" VARCHAR2(2), 
	"ROWC" NUMBER, 
	"SRCFILELINENO" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."ID" IS 'Codigo interno del sistema'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."AGREEMENTSERVICEID" IS 'Identificador del servicio por contrato original'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."FRQUNCYGNRTEACCNT" IS 'Frecuencia de genracion de extracto'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."NOTEDELIVERY" IS 'Indicador de entrega de nota'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."MAGNETICSHIP" IS 'Indicador envio magnetico'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."BALANCE" IS 'Saldo actual'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."BALANCEAVERAGE" IS 'Orden de generacion de los detalles'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."LASTDAYBALANCE" IS 'Saldo dia anterior'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."MONTHDEBITS" IS 'Debitos mes'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."MONTHCREDITS" IS 'Creditos mes'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."DEBTISVALUE" IS 'Valor debitos'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."CREDITVALUES" IS 'Valor creditos'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."OVERDRAFTTAX" IS 'Tasa de interes de sobregiro'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."PRINTACCNT" IS 'Indicador de impresion'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."CARDSTATUS" IS 'Estado de la tarjeta'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."LOOKSTATUS" IS 'Estado de bloqueo'
   COMMENT ON COLUMN "EWS$BNKAGREEMENTSERVICE"."SRCFILELINENO" IS 'Numero linea archivo fuente'
--------------------------------------------------------
--  DDL for Table EWS$BNKDOCUMENTDETAIL
--------------------------------------------------------

  CREATE TABLE "EWS$BNKDOCUMENTDETAIL" 
   (	"ID" NUMBER, 
	"DOCUMENTDETAILID" NUMBER, 
	"VOUCHERCODE" VARCHAR2(16), 
	"STORELISTID" NUMBER, 
	"CITYID" NUMBER, 
	"INSTALLMENT" NUMBER, 
	"DEFERREDBALANCE" NUMBER(18,5), 
	"TERM" NUMBER(2,0), 
	"NUMBERQUOTE" NUMBER(3,0), 
	"PENDQUOTE" NUMBER(3,0), 
	"DOCUMENTCODE" VARCHAR2(8), 
	"REASONRETURN4EXCHNG" VARCHAR2(2), 
	"CHANNEL" NUMBER, 
	"AGREEMENTID" NUMBER, 
	"ROWC" NUMBER, 
	"SRCFILELINENO" NUMBER, 
	"YEAR" NUMBER(4,0), 
	"MONTH" NUMBER(2,0), 
	"PRINTCLOSETYPE" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$BNKDOCUMENTDETAIL"."SRCFILELINENO" IS 'Numero linea archivo fuente'
   COMMENT ON COLUMN "EWS$BNKDOCUMENTDETAIL"."YEAR" IS 'Año corte impresion extracto'
   COMMENT ON COLUMN "EWS$BNKDOCUMENTDETAIL"."MONTH" IS 'Mes corte impresion extractos'
   COMMENT ON COLUMN "EWS$BNKDOCUMENTDETAIL"."PRINTCLOSETYPE" IS 'Tipo corte impresion extractos'
--------------------------------------------------------
--  DDL for Table EWS$BNKMASTERSTORAGE
--------------------------------------------------------

  CREATE TABLE "EWS$BNKMASTERSTORAGE" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"CODE" VARCHAR2(4), 
	"YEAR" NUMBER, 
	"JULIAN" NUMBER, 
	"STATUS" VARCHAR2(1), 
	"THREADS" NUMBER(2,0), 
	"SERVICETYPEID" NUMBER, 
	"FILECONTROLID" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."ID" IS 'Codigo interno del sistema'
   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."COMPANYID" IS 'Codigo interno de la Compa?ia'
   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."CODE" IS 'Codigo de la tabla'
   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."YEAR" IS 'A?o de ejecucion'
   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."JULIAN" IS 'Fecha Julian'
   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."STATUS" IS 'Estados'
   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."SERVICETYPEID" IS 'Tipo de servicio eis$servicetype'
   COMMENT ON COLUMN "EWS$BNKMASTERSTORAGE"."FILECONTROLID" IS 'Archivo de control'
--------------------------------------------------------
--  DDL for Table EWS$DOCUMENT
--------------------------------------------------------

  CREATE TABLE "EWS$DOCUMENT" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"ACCOUNTBALANCEID" NUMBER, 
	"DOCUMENTTYPEID" NUMBER, 
	"CODE" VARCHAR2(16), 
	"AGREEMENTID" NUMBER, 
	"SERVICEID" NUMBER, 
	"SUBSCRIBERSERVICEID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"BILLCYCLEID" NUMBER, 
	"BILLPERIODID" NUMBER, 
	"YEAR" NUMBER(4,0), 
	"MONTH" NUMBER(2,0), 
	"CREATEDATE" DATE, 
	"MONEYID" NUMBER, 
	"VALUE" NUMBER(18,5), 
	"RETENTIONTAX" NUMBER(18,5), 
	"DETAILS" NUMBER, 
	"ROWC" NUMBER
   )
--------------------------------------------------------
--  DDL for Table EWS$DOCUMENTDETAIL
--------------------------------------------------------

  CREATE TABLE "EWS$DOCUMENTDETAIL" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"ACCOUNTBALANCEID" NUMBER, 
	"DOCUMENTID" NUMBER, 
	"AGREEMENTID" NUMBER, 
	"SERVICEID" NUMBER, 
	"SUBSCRIBERSERVICEID" NUMBER, 
	"SERVICEUSERID" NUMBER, 
	"BILLCYCLEID" NUMBER, 
	"BILLPERIODID" NUMBER, 
	"MOVEMENTPERIODID" NUMBER, 
	"YEAR" NUMBER(4,0), 
	"MONTH" NUMBER(2,0), 
	"REFERENCEDOCUMENTID" NUMBER, 
	"ACCOUNTINGDATE" DATE, 
	"BILLINGPLANID" NUMBER, 
	"CONCEPTID" NUMBER, 
	"FORMULAID" NUMBER, 
	"OPERATIONID" NUMBER, 
	"TAXPERCENTAGEID" NUMBER, 
	"RATEOFCHANGEID" NUMBER, 
	"TORATEOFCHANGEID" NUMBER, 
	"MONEYID" NUMBER, 
	"MONEYVALUE" NUMBER(18,5), 
	"SIGN" VARCHAR2(1), 
	"MEASUREMENTUNITID" NUMBER, 
	"UNITS" NUMBER(18,2), 
	"VALUE" NUMBER(18,5), 
	"TAXVALUE" NUMBER(18,5), 
	"DISCOUNTVALUE" NUMBER(18,5), 
	"PROCESSID" NUMBER, 
	"USERID" NUMBER, 
	"CREATEDATE" DATE, 
	"STATUS" VARCHAR2(1), 
	"ROWC" NUMBER, 
	"REFERENCESOURCE" NUMBER
   )
--------------------------------------------------------
--  DDL for Table EWS$DOUBTFUL4COLLECT
--------------------------------------------------------

  CREATE TABLE "EWS$DOUBTFUL4COLLECT" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"AGREEMENTSERVICEID" NUMBER, 
	"ACCOUNTDOUBTFUL" NUMBER, 
	"BALANCE4CLLCTALLPERIOD" NUMBER(18,5), 
	"FROMDATE4CLLCTALLPERIOD" DATE, 
	"BALANCE4CLLCTPERIODACCNT" NUMBER(18,5), 
	"FROMDATE4CLLCTPERIODACCNT" DATE, 
	"ROWC" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."ID" IS 'Codigo interno'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."COMPANYID" IS 'Apuntador a la compa?ia'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."AGREEMENTSERVICEID" IS 'Apuntador al servicio x contrato'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."ACCOUNTDOUBTFUL" IS 'Numero estados de cuenta morosas'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."BALANCE4CLLCTALLPERIOD" IS 'Saldo liquidar morosidad todo el periodo (Estado de cuenta periodos anteriores)'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."FROMDATE4CLLCTALLPERIOD" IS 'Fecha inicial para cobro de la morosidad'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."BALANCE4CLLCTPERIODACCNT" IS 'Saldo moroso estado de cuenta del periodo abierto'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."FROMDATE4CLLCTPERIODACCNT" IS 'Fecha inicial para cobro de morosidad del saldo moroso del periodo(fecha limite pago, fecha ultimo pago)'
   COMMENT ON COLUMN "EWS$DOUBTFUL4COLLECT"."ROWC" IS 'Numero fila para procesamiento'
--------------------------------------------------------
--  DDL for Table EWS$DOUBTFULRECHARGE
--------------------------------------------------------

  CREATE TABLE "EWS$DOUBTFULRECHARGE" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"AGREEMENTSERVICEID" NUMBER, 
	"ACCOUNTBALANCEID" NUMBER, 
	"DOUBTFULDAYS" NUMBER, 
	"VALUE" NUMBER, 
	"STATUS" VARCHAR2(1), 
	"RATEDATEDOUBTFUL" DATE, 
	"ROWC" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."ID" IS 'Codigo interno'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."COMPANYID" IS 'Apuntador a compa?ia'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."AGREEMENTSERVICEID" IS 'Apuntador a contrato/servicio'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."ACCOUNTBALANCEID" IS 'Apuntador interno a estados de cuenta'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."DOUBTFULDAYS" IS 'Numero dias de mora pago atrasado'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."VALUE" IS 'Valor'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."STATUS" IS 'Estado de proceso : O - pendiente procesar(OPEN), C - Procesado(CLOSED)'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."RATEDATEDOUBTFUL" IS 'Fecha liquidacion recargo por mora'
   COMMENT ON COLUMN "EWS$DOUBTFULRECHARGE"."ROWC" IS 'Numero de fila'
--------------------------------------------------------
--  DDL for Table EWS$MASTERSTORAGE
--------------------------------------------------------

  CREATE TABLE "EWS$MASTERSTORAGE" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"CODE" VARCHAR2(4), 
	"BILLCYCLEID" NUMBER, 
	"BILLPERIODID" NUMBER, 
	"STATUS" VARCHAR2(1), 
	"THREADS" NUMBER(2,0)
   )
--------------------------------------------------------
--  DDL for Table EWS$PREVALUEDCHARGES4BILL
--------------------------------------------------------

  CREATE TABLE "EWS$PREVALUEDCHARGES4BILL" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"AGREEMENTID" NUMBER, 
	"SERVICEID" NUMBER, 
	"SUBSCRIBERSERVICEID" NUMBER, 
	"BILLCYCLEID" NUMBER, 
	"MOVEMENTPERIODID" NUMBER, 
	"REFERENCESOURCE" NUMBER, 
	"REFERENCEDOCUMENTID" NUMBER, 
	"BILLINGPLANID" NUMBER, 
	"FORMULAID" NUMBER, 
	"OPERATIONID" NUMBER, 
	"TAXPERCENTAGEID" NUMBER, 
	"RATEOFCHANGEID" NUMBER, 
	"TORATEOFCHANGEID" NUMBER, 
	"MONEYID" NUMBER, 
	"MONEYVALUE" NUMBER(18,5), 
	"SIGN" VARCHAR2(1), 
	"UNITS" NUMBER(18,2), 
	"VALUE" NUMBER(18,5), 
	"TAXVALUE" NUMBER(18,5), 
	"DISCOUNTVALUE" NUMBER(18,5), 
	"CREATEDATE" DATE, 
	"STATUS" VARCHAR2(1), 
	"ROWC" NUMBER
   ) 

   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."ID" IS 'Codigo interno'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."COMPANYID" IS 'Apuntador a la compa?ia'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."AGREEMENTID" IS 'Apuntador al contrato'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."SERVICEID" IS 'Apuntador al servicio; servicio involucrado en el cobro del concepto'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."SUBSCRIBERSERVICEID" IS 'Apuntador al servicio suscrito'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."BILLCYCLEID" IS 'Apuntador al ciclo de facturacion'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."MOVEMENTPERIODID" IS 'Apuntador al periodo de facturacion registra el movimiento'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."REFERENCESOURCE" IS 'Objecto de refencia (1 - Documento, 2 - Estado cuenta, 3 - Financiacion)'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."REFERENCEDOCUMENTID" IS 'Apuntador al id del objeto de referencia'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."BILLINGPLANID" IS 'Apuntador al plan de facturacion'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."FORMULAID" IS 'Apuntador a la formula'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."OPERATIONID" IS 'Apuntador a la operacion contable'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."TAXPERCENTAGEID" IS 'Apuntador al porcentaje de impuesto'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."RATEOFCHANGEID" IS 'Apuntador origen de tasa de cambio'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."TORATEOFCHANGEID" IS 'Apuntador destino de tasa de cambio'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."MONEYID" IS 'Apuntador a la moneda define tarifa'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."MONEYVALUE" IS 'Valor liquidado en la moneda de la tarifa'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."SIGN" IS 'Signo'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."UNITS" IS 'Unidades involucradas en la liquidacion del cobro'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."VALUE" IS 'Valor liquidado en la moneda de cobro(definida en el contrato)'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."TAXVALUE" IS 'Valor impuesto'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."DISCOUNTVALUE" IS 'Valor descuento'
   COMMENT ON COLUMN "EWS$PREVALUEDCHARGES4BILL"."CREATEDATE" IS 'Fecha creacion del cobro'
--------------------------------------------------------
--  DDL for Table EWS$SHELFSTORAGE
--------------------------------------------------------

  CREATE TABLE "EWS$SHELFSTORAGE" 
   (	"ID" NUMBER, 
	"COMPANYID" NUMBER, 
	"MASTERSTORAGEID" NUMBER, 
	"CODE" VARCHAR2(4), 
	"SERVICEID" NUMBER, 
	"CONCEPTID" NUMBER, 
	"THREADS" NUMBER(2,0), 
	"STATUS" VARCHAR2(1)
   )
--------------------------------------------------------
--  DDL for Index EWS$BNKACCOUNTBALANCE_K1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$BNKACCOUNTBALANCE_K1" ON "EWS$BNKACCOUNTBALANCE" ("SUBSCRIBERSERVICEID", "CODE", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKACCOUNTBALANCE_K2
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$BNKACCOUNTBALANCE_K2" ON "EWS$BNKACCOUNTBALANCE" ("ID", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKACCOUNTBALANCE_X1
--------------------------------------------------------

  CREATE INDEX "EWS$BNKACCOUNTBALANCE_X1" ON "EWS$BNKACCOUNTBALANCE" ("AGREEMENTID", "MONEYID", "ROWC")
--------------------------------------------------------
--  DDL for Index EWS$BNKACCOUNTBALANCE_X2
--------------------------------------------------------

  CREATE INDEX "EWS$BNKACCOUNTBALANCE_X2" ON "EWS$BNKACCOUNTBALANCE" ("ROWC", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKADDTNALDCMENTDTIL_X1
--------------------------------------------------------

  CREATE INDEX "EWS$BNKADDTNALDCMENTDTIL_X1" ON "EWS$BNKADDTNALDCMENTDTIL" ("AGREEMENTID", "ROWC")
--------------------------------------------------------
--  DDL for Index EWS$BNKADDTNALDCMENTDTIL_X2
--------------------------------------------------------

  CREATE INDEX "EWS$BNKADDTNALDCMENTDTIL_X2" ON "EWS$BNKADDTNALDCMENTDTIL" ("ROWC", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKADDTNALDCMENTDTIL_IK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$BNKADDTNALDCMENTDTIL_IK" ON "EWS$BNKADDTNALDCMENTDTIL" ("ID")
--------------------------------------------------------
--  DDL for Index EWS$BNKAGREEMENTSERVICE_K1
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$BNKAGREEMENTSERVICE_K1" ON "EWS$BNKAGREEMENTSERVICE" ("SUBSCRIBERSERVICEID", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKAGREEMENTSERVICE_K2
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$BNKAGREEMENTSERVICE_K2" ON "EWS$BNKAGREEMENTSERVICE" ("ID", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKAGREEMENTSERVICE_X1
--------------------------------------------------------

  CREATE INDEX "EWS$BNKAGREEMENTSERVICE_X1" ON "EWS$BNKAGREEMENTSERVICE" ("AGREEMENTID", "ROWC")
--------------------------------------------------------
--  DDL for Index EWS$BNKAGREEMENTSERVICE_X2
--------------------------------------------------------

  CREATE INDEX "EWS$BNKAGREEMENTSERVICE_X2" ON "EWS$BNKAGREEMENTSERVICE" ("ROWC", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKDOCUMENTDETAIL_X1
--------------------------------------------------------

  CREATE INDEX "EWS$BNKDOCUMENTDETAIL_X1" ON "EWS$BNKDOCUMENTDETAIL" ("AGREEMENTID", "ROWC")
--------------------------------------------------------
--  DDL for Index EWS$BNKDOCUMENTDETAIL_X2
--------------------------------------------------------

  CREATE INDEX "EWS$BNKDOCUMENTDETAIL_X2" ON "EWS$BNKDOCUMENTDETAIL" ("ROWC", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$BNKDOCUMENTDETAIL_IK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$BNKDOCUMENTDETAIL_IK" ON "EWS$BNKDOCUMENTDETAIL" ("ID")
--------------------------------------------------------
--  DDL for Index EWS$BNKMASTERSTORAGE_IK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$BNKMASTERSTORAGE_IK" ON "EWS$BNKMASTERSTORAGE" ("ID")
--------------------------------------------------------
--  DDL for Index EWS$BNKMASTERSTORAGE_X1
--------------------------------------------------------

  CREATE INDEX "EWS$BNKMASTERSTORAGE_X1" ON "EWS$BNKMASTERSTORAGE" ("SERVICETYPEID", "JULIAN")
--------------------------------------------------------
--  DDL for Index EWS$DOCUMENT_X1
--------------------------------------------------------

  CREATE INDEX "EWS$DOCUMENT_X1" ON "EWS$DOCUMENT" ("COMPANYID", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$DOCUMENT_IK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$DOCUMENT_IK" ON "EWS$DOCUMENT" ("ID")
--------------------------------------------------------
--  DDL for Index EWS$DOCUMENTDETAIL_X1
--------------------------------------------------------

  CREATE INDEX "EWS$DOCUMENTDETAIL_X1" ON "EWS$DOCUMENTDETAIL" ("ACCOUNTBALANCEID", "ACCOUNTINGDATE", "CREATEDATE", "OPERATIONID")
--------------------------------------------------------
--  DDL for Index EWS$DOCUMENTDETAIL_X2
--------------------------------------------------------

  CREATE INDEX "EWS$DOCUMENTDETAIL_X2" ON "EWS$DOCUMENTDETAIL" ("SUBSCRIBERSERVICEID")
--------------------------------------------------------
--  DDL for Index EWS$DOCUMENTDETAIL_X3
--------------------------------------------------------

  CREATE INDEX "EWS$DOCUMENTDETAIL_X3" ON "EWS$DOCUMENTDETAIL" ("AGREEMENTID", "ROWC")
--------------------------------------------------------
--  DDL for Index EWS$DOCUMENTDETAIL_X4
--------------------------------------------------------

  CREATE INDEX "EWS$DOCUMENTDETAIL_X4" ON "EWS$DOCUMENTDETAIL" ("ROWC", "AGREEMENTID")
--------------------------------------------------------
--  DDL for Index EWS$DOCUMENTDETAIL_IK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$DOCUMENTDETAIL_IK" ON "EWS$DOCUMENTDETAIL" ("ID")
--------------------------------------------------------
--  DDL for Index EWS$DOUBTFUL4COLLECT_IK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$DOUBTFUL4COLLECT_IK" ON "EWS$DOUBTFUL4COLLECT" ("ID")
--------------------------------------------------------
--  DDL for Index EWS$DOUBTFULRECHARGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$DOUBTFULRECHARGE" ON "EWS$DOUBTFULRECHARGE" ("ID")
--------------------------------------------------------
--  DDL for Index EWS$PREVALUEDCHARGES4BILL_IK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EWS$PREVALUEDCHARGES4BILL_IK" ON "EWS$PREVALUEDCHARGES4BILL" ("ID")
--------------------------------------------------------
--  Constraints for Table EWS$ACCOUNTBALANCE
--------------------------------------------------------

  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("BALANCEAGREEAFTERBILL" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("BALANCEAGREEBEROFEBILL" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("BALANCE" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("MONEYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("PAYMENTDATELIMIT" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("CREATEDDATE" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("MONTH" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("YEAR" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("BILLPERIODID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("BILLCYCLEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("SERVICEUSERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("SUBSCRIBERSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("CODE" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$ACCOUNTBALANCE" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$AGREEMENT
--------------------------------------------------------

  ALTER TABLE "EWS$AGREEMENT" MODIFY ("BALANCE2AGREE" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENT" MODIFY ("BALANCE2COMPANY" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENT" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENT" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$AGREEMENTSERVICE
--------------------------------------------------------

  ALTER TABLE "EWS$AGREEMENTSERVICE" MODIFY ("BALANCE2COMPANY" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICE" MODIFY ("PENDINGACCOUNTS" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICE" MODIFY ("SUBSCRIBERSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICE" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICE" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICE" MODIFY ("COMPANYID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$AGREEMENTSERVICEUSER
--------------------------------------------------------

  ALTER TABLE "EWS$AGREEMENTSERVICEUSER" MODIFY ("BALANCE2COMPANY" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICEUSER" MODIFY ("PENDINGACCOUNTS" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICEUSER" MODIFY ("SERVICEUSERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICEUSER" MODIFY ("AGREEMENTSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTSERVICEUSER" MODIFY ("COMPANYID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$AGREEMENTUSER
--------------------------------------------------------

  ALTER TABLE "EWS$AGREEMENTUSER" MODIFY ("BALANCE2USER" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTUSER" MODIFY ("BALANCE2COMPANY" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTUSER" MODIFY ("SERVICEUSERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTUSER" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$AGREEMENTUSER" MODIFY ("COMPANYID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$BNKACCOUNTBALANCE
--------------------------------------------------------

  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("PRINTDETAILID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("MONEYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("PAYMENTDATELIMIT" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("CREATEDDATE" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("MONTH" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("YEAR" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("BILLCYCLEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("SERVICEUSERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("SUBSCRIBERSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("CODE" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKACCOUNTBALANCE" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$BNKADDTNALDCMENTDTIL
--------------------------------------------------------

  ALTER TABLE "EWS$BNKADDTNALDCMENTDTIL" ADD CONSTRAINT "EWS$BNKADDTNALDCMENTDTIL_IK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$BNKADDTNALDCMENTDTIL" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKADDTNALDCMENTDTIL" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$BNKAGREEMENTSERVICE
--------------------------------------------------------

  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("STATUSID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("FROMDATE" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("PENDINGACCOUNTS" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("USERPAYMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("SERVICEUSERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("SUBSCRIBERSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("AGREEMENTSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKAGREEMENTSERVICE" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$BNKDOCUMENTDETAIL
--------------------------------------------------------

  ALTER TABLE "EWS$BNKDOCUMENTDETAIL" ADD CONSTRAINT "EWS$BNKDOCUMENTDETAIL_IK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$BNKDOCUMENTDETAIL" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKDOCUMENTDETAIL" MODIFY ("DOCUMENTDETAILID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKDOCUMENTDETAIL" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$BNKMASTERSTORAGE
--------------------------------------------------------

  ALTER TABLE "EWS$BNKMASTERSTORAGE" ADD CONSTRAINT "EWS$BNKMASTERSTORAGE_IK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$BNKMASTERSTORAGE" MODIFY ("THREADS" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKMASTERSTORAGE" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKMASTERSTORAGE" MODIFY ("JULIAN" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKMASTERSTORAGE" MODIFY ("YEAR" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKMASTERSTORAGE" MODIFY ("CODE" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKMASTERSTORAGE" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$BNKMASTERSTORAGE" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$DOCUMENT
--------------------------------------------------------

  ALTER TABLE "EWS$DOCUMENT" ADD CONSTRAINT "EWS$DOCUMENT_IK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("DETAILS" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("MONEYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("CREATEDATE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("MONTH" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("YEAR" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("BILLPERIODID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("BILLCYCLEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("SERVICEUSERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("SUBSCRIBERSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("CODE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("DOCUMENTTYPEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("ACCOUNTBALANCEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENT" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$DOCUMENTDETAIL
--------------------------------------------------------

  ALTER TABLE "EWS$DOCUMENTDETAIL" ADD CONSTRAINT "EWS$DOCUMENTDETAIL_IK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("CREATEDATE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("USERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("PROCESSID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("DISCOUNTVALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("TAXVALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("SIGN" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("MONEYVALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("MONEYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("TAXPERCENTAGEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("OPERATIONID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("FORMULAID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("CONCEPTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("BILLINGPLANID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("ACCOUNTINGDATE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("MONTH" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("YEAR" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("MOVEMENTPERIODID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("BILLPERIODID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("BILLCYCLEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("SERVICEUSERID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("SUBSCRIBERSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("DOCUMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOCUMENTDETAIL" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$DOUBTFUL4COLLECT
--------------------------------------------------------

  ALTER TABLE "EWS$DOUBTFUL4COLLECT" ADD CONSTRAINT "EWS$DOUBTFUL4COLLECT_IK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("FROMDATE4CLLCTPERIODACCNT" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("BALANCE4CLLCTPERIODACCNT" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("FROMDATE4CLLCTALLPERIOD" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("BALANCE4CLLCTALLPERIOD" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("ACCOUNTDOUBTFUL" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("AGREEMENTSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFUL4COLLECT" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$DOUBTFULRECHARGE
--------------------------------------------------------

  ALTER TABLE "EWS$DOUBTFULRECHARGE" ADD CONSTRAINT "EWS$DOUBTFULRECHARGE" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$DOUBTFULRECHARGE" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFULRECHARGE" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFULRECHARGE" MODIFY ("DOUBTFULDAYS" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFULRECHARGE" MODIFY ("ACCOUNTBALANCEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFULRECHARGE" MODIFY ("AGREEMENTSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFULRECHARGE" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$DOUBTFULRECHARGE" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$MASTERSTORAGE
--------------------------------------------------------

  ALTER TABLE "EWS$MASTERSTORAGE" MODIFY ("THREADS" NOT NULL ENABLE)
  ALTER TABLE "EWS$MASTERSTORAGE" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "EWS$MASTERSTORAGE" MODIFY ("BILLPERIODID" NOT NULL ENABLE)
  ALTER TABLE "EWS$MASTERSTORAGE" MODIFY ("BILLCYCLEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$MASTERSTORAGE" MODIFY ("CODE" NOT NULL ENABLE)
  ALTER TABLE "EWS$MASTERSTORAGE" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$MASTERSTORAGE" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$PREVALUEDCHARGES4BILL
--------------------------------------------------------

  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" ADD CONSTRAINT "EWS$PREVALUEDCHARGES4BILL_IK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("ROWC" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("CREATEDATE" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("DISCOUNTVALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("TAXVALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("SIGN" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("MONEYVALUE" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("MONEYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("TORATEOFCHANGEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("RATEOFCHANGEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("TAXPERCENTAGEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("OPERATIONID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("FORMULAID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("BILLINGPLANID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("MOVEMENTPERIODID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("BILLCYCLEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("SUBSCRIBERSERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("AGREEMENTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$PREVALUEDCHARGES4BILL" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EWS$SHELFSTORAGE
--------------------------------------------------------

  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("THREADS" NOT NULL ENABLE)
  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("CONCEPTID" NOT NULL ENABLE)
  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("SERVICEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("CODE" NOT NULL ENABLE)
  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("MASTERSTORAGEID" NOT NULL ENABLE)
  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "EWS$SHELFSTORAGE" MODIFY ("ID" NOT NULL ENABLE)
